---
swagger: "2.0"
info:
  description: "An OpenAPI for EVE Online"
  version: "1.7.14"
  title: "EVE Swagger Interface"
host: "esi.evetech.net"
basePath: "/v2"
schemes:
- "https"
paths:
  /alliances/:
    get:
      tags:
      - "Alliance"
      summary: "List all alliances"
      description: "List all active player alliances\n\n---\nAlternate route: `/dev/alliances/`\n\
        \nAlternate route: `/latest/alliances/`\n\nAlternate route: `/legacy/alliances/`\n\
        \nAlternate route: `/v1/alliances/`\n\n---\nThis route is cached for up to\
        \ 3600 seconds"
      operationId: "get_alliances"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /alliances/{alliance_id}/contacts/:
    get:
      tags:
      - "Contacts"
      summary: "Get alliance contacts"
      description: "Return contacts of an alliance\n\n---\nAlternate route: `/dev/alliances/{alliance_id}/contacts/`\n\
        \nAlternate route: `/latest/alliances/{alliance_id}/contacts/`\n\n---\nThis\
        \ route is cached for up to 300 seconds"
      operationId: "get_alliances_alliance_id_contacts"
      security:
      - evesso:
        - "esi-alliances.read_contacts.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 300
  /alliances/{alliance_id}/corporations/:
    get:
      tags:
      - "Alliance"
      summary: "List alliance's corporations"
      description: "List all current member corporations of an alliance\n\n---\nAlternate\
        \ route: `/dev/alliances/{alliance_id}/corporations/`\n\nAlternate route:\
        \ `/latest/alliances/{alliance_id}/corporations/`\n\nAlternate route: `/legacy/alliances/{alliance_id}/corporations/`\n\
        \nAlternate route: `/v1/alliances/{alliance_id}/corporations/`\n\n---\nThis\
        \ route is cached for up to 3600 seconds"
      operationId: "get_alliances_alliance_id_corporations"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /alliances/{alliance_id}/icons/:
    get:
      tags:
      - "Alliance"
      summary: "Get alliance icon"
      description: "Get the icon urls for a alliance\n\n---\nAlternate route: `/dev/alliances/{alliance_id}/icons/`\n\
        \n---\nThis route expires daily at 11:05"
      operationId: "get_alliances_alliance_id_icons"
      x-alternate-versions:
      - "dev"
  /characters/affiliation/:
    post:
      tags:
      - "Character"
      summary: "Character affiliation"
      description: "Bulk lookup of character IDs to corporation, alliance and faction\n\
        \n---\nAlternate route: `/dev/characters/affiliation/`\n\n---\nThis route\
        \ is cached for up to 3600 seconds"
      operationId: "post_characters_affiliation"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 3600
  /characters/{character_id}/agents_research/:
    get:
      tags:
      - "Character"
      summary: "Get agents research"
      description: "Return a list of agents research information for a character.\
        \ The formula for finding the current research points with an agent is: currentPoints\
        \ = remainderPoints + pointsPerDay * days(currentTime - researchStartDate)\n\
        \n---\nAlternate route: `/dev/characters/{character_id}/agents_research/`\n\
        \n---\nThis route is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_agents_research"
      security:
      - evesso:
        - "esi-characters.read_agents_research.v1"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 3600
  /characters/{character_id}/assets/locations/:
    post:
      tags:
      - "Assets"
      summary: "Get character asset locations"
      description: "Return locations for a set of item ids, which you can get from\
        \ character assets endpoint. Coordinates for items in hangars or stations\
        \ are set to (0,0,0)\n\n---\nAlternate route: `/dev/characters/{character_id}/assets/locations/`\n\
        \nAlternate route: `/latest/characters/{character_id}/assets/locations/`\n"
      operationId: "post_characters_character_id_assets_locations"
      security:
      - evesso:
        - "esi-assets.read_assets.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
  /characters/{character_id}/blueprints/:
    get:
      tags:
      - "Character"
      summary: "Get blueprints"
      description: "Return a list of blueprints the character owns\n\n---\nAlternate\
        \ route: `/latest/characters/{character_id}/blueprints/`\n\n---\nThis route\
        \ is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_blueprints"
      security:
      - evesso:
        - "esi-characters.read_blueprints.v1"
      x-alternate-versions:
      - "latest"
      x-cached-seconds: 3600
  /characters/{character_id}/bookmarks/:
    get:
      tags:
      - "Bookmarks"
      summary: "List bookmarks"
      description: "A list of your character's personal bookmarks\n\n---\nAlternate\
        \ route: `/dev/characters/{character_id}/bookmarks/`\n\nAlternate route: `/latest/characters/{character_id}/bookmarks/`\n\
        \n---\nThis route is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_bookmarks"
      security:
      - evesso:
        - "esi-bookmarks.read_character_bookmarks.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
  /characters/{character_id}/bookmarks/folders/:
    get:
      tags:
      - "Bookmarks"
      summary: "List bookmark folders"
      description: "A list of your character's personal bookmark folders\n\n---\n\
        Alternate route: `/dev/characters/{character_id}/bookmarks/folders/`\n\nAlternate\
        \ route: `/latest/characters/{character_id}/bookmarks/folders/`\n\n---\nThis\
        \ route is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_bookmarks_folders"
      security:
      - evesso:
        - "esi-bookmarks.read_character_bookmarks.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
  /characters/{character_id}/calendar/:
    get:
      tags:
      - "Calendar"
      summary: "List calendar event summaries"
      description: "Get 50 event summaries from the calendar. If no from_event ID\
        \ is given, the resource will return the next 50 chronological event summaries\
        \ from now. If a from_event ID is specified, it will return the next 50 chronological\
        \ event summaries from after that event\n\n---\nAlternate route: `/dev/characters/{character_id}/calendar/`\n\
        \nAlternate route: `/latest/characters/{character_id}/calendar/`\n\nAlternate\
        \ route: `/legacy/characters/{character_id}/calendar/`\n\nAlternate route:\
        \ `/v1/characters/{character_id}/calendar/`\n\n---\nThis route is cached for\
        \ up to 5 seconds"
      operationId: "get_characters_character_id_calendar"
      security:
      - evesso:
        - "esi-calendar.read_calendar_events.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v1"
      x-cached-seconds: 5
  /characters/{character_id}/calendar/{event_id}/attendees/:
    get:
      tags:
      - "Calendar"
      summary: "Get attendees"
      description: "Get all invited attendees for a given event\n\n---\nAlternate\
        \ route: `/dev/characters/{character_id}/calendar/{event_id}/attendees/`\n\
        \nAlternate route: `/latest/characters/{character_id}/calendar/{event_id}/attendees/`\n\
        \nAlternate route: `/legacy/characters/{character_id}/calendar/{event_id}/attendees/`\n\
        \nAlternate route: `/v1/characters/{character_id}/calendar/{event_id}/attendees/`\n\
        \n---\nThis route is cached for up to 600 seconds"
      operationId: "get_characters_character_id_calendar_event_id_attendees"
      security:
      - evesso:
        - "esi-calendar.read_calendar_events.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v1"
      x-cached-seconds: 600
  /characters/{character_id}/clones/:
    get:
      tags:
      - "Clones"
      summary: "Get clones"
      description: "A list of the character's clones\n\n---\nAlternate route: `/legacy/characters/{character_id}/clones/`\n\
        \n---\nThis route is cached for up to 120 seconds\n\n---\nWarning: This route\
        \ is deprecated\n\n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/v2/dev/#GET-/characters/{character_id}/clones/)"
      operationId: "get_characters_character_id_clones"
      security:
      - evesso:
        - "esi-clones.read_clones.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
      x-cached-seconds: 120
  /characters/{character_id}/contacts/:
    get:
      tags:
      - "Contacts"
      summary: "Get contacts"
      description: "Return contacts of a character\n\n---\nAlternate route: `/dev/characters/{character_id}/contacts/`\n\
        \nAlternate route: `/latest/characters/{character_id}/contacts/`\n\n---\n\
        This route is cached for up to 300 seconds"
      operationId: "get_characters_character_id_contacts"
      security:
      - evesso:
        - "esi-characters.read_contacts.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 300
    post:
      tags:
      - "Contacts"
      summary: "Add contacts"
      description: "Bulk add contacts with same settings\n\n---\nAlternate route:\
        \ `/dev/characters/{character_id}/contacts/`\n\nAlternate route: `/latest/characters/{character_id}/contacts/`\n"
      operationId: "post_characters_character_id_contacts"
      security:
      - evesso:
        - "esi-characters.write_contacts.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
    put:
      tags:
      - "Contacts"
      summary: "Edit contacts"
      description: "Bulk edit contacts with same settings\n\n---\nAlternate route:\
        \ `/dev/characters/{character_id}/contacts/`\n\nAlternate route: `/latest/characters/{character_id}/contacts/`\n"
      operationId: "put_characters_character_id_contacts"
      security:
      - evesso:
        - "esi-characters.write_contacts.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
    delete:
      tags:
      - "Contacts"
      summary: "Delete contacts"
      description: "Bulk delete contacts\n\n---\nAlternate route: `/dev/characters/{character_id}/contacts/`\n\
        \nAlternate route: `/latest/characters/{character_id}/contacts/`\n"
      operationId: "delete_characters_character_id_contacts"
      security:
      - evesso:
        - "esi-characters.write_contacts.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
  /characters/{character_id}/corporationhistory/:
    get:
      tags:
      - "Character"
      summary: "Get corporation history"
      description: "Get a list of all the corporations a character has been a member\
        \ of\n\n---\nAlternate route: `/dev/characters/{character_id}/corporationhistory/`\n\
        \n---\nThis route is cached for up to 86400 seconds"
      operationId: "get_characters_character_id_corporationhistory"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 86400
  /characters/{character_id}/fatigue/:
    get:
      tags:
      - "Character"
      summary: "Get jump fatigue"
      description: "Return a character's jump activation and fatigue information\n\
        \n---\nAlternate route: `/dev/characters/{character_id}/fatigue/`\n\n---\n\
        This route is cached for up to 300 seconds"
      operationId: "get_characters_character_id_fatigue"
      security:
      - evesso:
        - "esi-characters.read_fatigue.v1"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 300
  /characters/{character_id}/fittings/:
    get:
      tags:
      - "Fittings"
      summary: "Get fittings"
      description: "Return fittings of a character\n\n---\nAlternate route: `/dev/characters/{character_id}/fittings/`\n\
        \nAlternate route: `/latest/characters/{character_id}/fittings/`\n\n---\n\
        This route is cached for up to 300 seconds"
      operationId: "get_characters_character_id_fittings"
      security:
      - evesso:
        - "esi-fittings.read_fittings.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 300
    post:
      tags:
      - "Fittings"
      summary: "Create fitting"
      description: "Save a new fitting for a character\n\n---\nAlternate route: `/dev/characters/{character_id}/fittings/`\n\
        \nAlternate route: `/latest/characters/{character_id}/fittings/`\n"
      operationId: "post_characters_character_id_fittings"
      security:
      - evesso:
        - "esi-fittings.write_fittings.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
  /characters/{character_id}/fleet/:
    get:
      tags:
      - "Fleets"
      summary: "Get character fleet info"
      description: "Return the fleet ID the character is in, if any.\n\n---\nAlternate\
        \ route: `/dev/characters/{character_id}/fleet/`\n\n---\nThis route is cached\
        \ for up to 60 seconds"
      operationId: "get_characters_character_id_fleet"
      security:
      - evesso:
        - "esi-fleets.read_fleet.v1"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 60
  /characters/{character_id}/fw/stats/:
    get:
      tags:
      - "Faction Warfare"
      summary: "Overview of a character involved in faction warfare"
      description: "Statistical overview of a character involved in faction warfare\n\
        \n---\nAlternate route: `/dev/characters/{character_id}/fw/stats/`\n\nAlternate\
        \ route: `/latest/characters/{character_id}/fw/stats/`\n\nAlternate route:\
        \ `/legacy/characters/{character_id}/fw/stats/`\n\nAlternate route: `/v1/characters/{character_id}/fw/stats/`\n\
        \n---\nThis route expires daily at 11:05"
      operationId: "get_characters_character_id_fw_stats"
      security:
      - evesso:
        - "esi-characters.read_fw_stats.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v1"
  /characters/{character_id}/implants/:
    get:
      tags:
      - "Clones"
      summary: "Get active implants"
      description: "Return implants on the active clone of a character\n\n---\nAlternate\
        \ route: `/dev/characters/{character_id}/implants/`\n\nAlternate route: `/latest/characters/{character_id}/implants/`\n\
        \nAlternate route: `/legacy/characters/{character_id}/implants/`\n\nAlternate\
        \ route: `/v1/characters/{character_id}/implants/`\n\n---\nThis route is cached\
        \ for up to 120 seconds"
      operationId: "get_characters_character_id_implants"
      security:
      - evesso:
        - "esi-clones.read_implants.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v1"
      x-cached-seconds: 120
  /characters/{character_id}/location/:
    get:
      tags:
      - "Location"
      summary: "Get character location"
      description: "Information about the characters current location. Returns the\
        \ current solar system id, and also the current station or structure ID if\
        \ applicable\n\n---\nAlternate route: `/dev/characters/{character_id}/location/`\n\
        \nAlternate route: `/latest/characters/{character_id}/location/`\n\nAlternate\
        \ route: `/legacy/characters/{character_id}/location/`\n\nAlternate route:\
        \ `/v1/characters/{character_id}/location/`\n\n---\nThis route is cached for\
        \ up to 5 seconds"
      operationId: "get_characters_character_id_location"
      security:
      - evesso:
        - "esi-location.read_location.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v1"
      x-cached-seconds: 5
  /characters/{character_id}/mail/labels/:
    get:
      tags:
      - "Mail"
      summary: "Get mail labels"
      description: "Return a list of the users mail labels\n\n---\nAlternate route:\
        \ `/legacy/characters/{character_id}/mail/labels/`\n\n---\nThis route is cached\
        \ for up to 30 seconds\n\n---\nWarning: This route is deprecated\n\n---\n\
        [Diff of the upcoming changes](https://esi.evetech.net/diff/v2/dev/#GET-/characters/{character_id}/mail/labels/)"
      operationId: "get_characters_character_id_mail_labels"
      security:
      - evesso:
        - "esi-mail.read_mail.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
      x-cached-seconds: 30
    post:
      tags:
      - "Mail"
      summary: "Create a mail label"
      description: "Create a mail label\n\n---\nAlternate route: `/dev/characters/{character_id}/mail/labels/`\n\
        \nAlternate route: `/latest/characters/{character_id}/mail/labels/`\n\nAlternate\
        \ route: `/legacy/characters/{character_id}/mail/labels/`\n"
      operationId: "post_characters_character_id_mail_labels"
      security:
      - evesso:
        - "esi-mail.organize_mail.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
  /characters/{character_id}/medals/:
    get:
      tags:
      - "Character"
      summary: "Get medals"
      description: "Return a list of medals the character has\n\n---\nAlternate route:\
        \ `/dev/characters/{character_id}/medals/`\n\n---\nThis route is cached for\
        \ up to 3600 seconds"
      operationId: "get_characters_character_id_medals"
      security:
      - evesso:
        - "esi-characters.read_medals.v1"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 3600
  /characters/{character_id}/notifications/contacts/:
    get:
      tags:
      - "Character"
      summary: "Get new contact notifications"
      description: "Return notifications about having been added to someone's contact\
        \ list\n\n---\nAlternate route: `/dev/characters/{character_id}/notifications/contacts/`\n\
        \n---\nThis route is cached for up to 600 seconds"
      operationId: "get_characters_character_id_notifications_contacts"
      security:
      - evesso:
        - "esi-characters.read_notifications.v1"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 600
  /characters/{character_id}/online/:
    get:
      tags:
      - "Location"
      summary: "Get character online"
      description: "Checks if the character is currently online\n\n---\nAlternate\
        \ route: `/dev/characters/{character_id}/online/`\n\nAlternate route: `/latest/characters/{character_id}/online/`\n\
        \nAlternate route: `/v3/characters/{character_id}/online/`\n\n---\nThis route\
        \ is cached for up to 60 seconds"
      operationId: "get_characters_character_id_online"
      security:
      - evesso:
        - "esi-location.read_online.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "v3"
      x-cached-seconds: 60
  /characters/{character_id}/orders/:
    get:
      tags:
      - "Market"
      summary: "List open orders from a character"
      description: "List open market orders placed by a character\n\n---\nAlternate\
        \ route: `/dev/characters/{character_id}/orders/`\n\nAlternate route: `/latest/characters/{character_id}/orders/`\n\
        \n---\nThis route is cached for up to 1200 seconds"
      operationId: "get_characters_character_id_orders"
      security:
      - evesso:
        - "esi-markets.read_character_orders.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 1200
  /characters/{character_id}/portrait/:
    get:
      tags:
      - "Character"
      summary: "Get character portraits"
      description: "Get portrait urls for a character\n\n---\nAlternate route: `/dev/characters/{character_id}/portrait/`\n\
        \nAlternate route: `/latest/characters/{character_id}/portrait/`\n\nAlternate\
        \ route: `/v3/characters/{character_id}/portrait/`\n\n---\nThis route expires\
        \ daily at 11:05"
      operationId: "get_characters_character_id_portrait"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "v3"
  /characters/{character_id}/roles/:
    get:
      tags:
      - "Character"
      summary: "Get character corporation roles"
      description: "Returns a character's corporation roles\n\n---\nAlternate route:\
        \ `/latest/characters/{character_id}/roles/`\n\n---\nThis route is cached\
        \ for up to 3600 seconds"
      operationId: "get_characters_character_id_roles"
      security:
      - evesso:
        - "esi-characters.read_corporation_roles.v1"
      x-alternate-versions:
      - "latest"
      x-cached-seconds: 3600
  /characters/{character_id}/ship/:
    get:
      tags:
      - "Location"
      summary: "Get current ship"
      description: "Get the current ship type, name and id\n\n---\nAlternate route:\
        \ `/dev/characters/{character_id}/ship/`\n\nAlternate route: `/latest/characters/{character_id}/ship/`\n\
        \nAlternate route: `/legacy/characters/{character_id}/ship/`\n\nAlternate\
        \ route: `/v1/characters/{character_id}/ship/`\n\n---\nThis route is cached\
        \ for up to 5 seconds"
      operationId: "get_characters_character_id_ship"
      security:
      - evesso:
        - "esi-location.read_ship_type.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v1"
      x-cached-seconds: 5
  /characters/{character_id}/skillqueue/:
    get:
      tags:
      - "Skills"
      summary: "Get character's skill queue"
      description: "List the configured skill queue for the given character\n\n---\n\
        Alternate route: `/dev/characters/{character_id}/skillqueue/`\n\nAlternate\
        \ route: `/latest/characters/{character_id}/skillqueue/`\n\nAlternate route:\
        \ `/legacy/characters/{character_id}/skillqueue/`\n\n---\nThis route is cached\
        \ for up to 120 seconds"
      operationId: "get_characters_character_id_skillqueue"
      security:
      - evesso:
        - "esi-skills.read_skillqueue.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      x-cached-seconds: 120
  /characters/{character_id}/standings/:
    get:
      tags:
      - "Character"
      summary: "Get standings"
      description: "Return character standings from agents, NPC corporations, and\
        \ factions\n\n---\nAlternate route: `/dev/characters/{character_id}/standings/`\n\
        \n---\nThis route is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_standings"
      security:
      - evesso:
        - "esi-characters.read_standings.v1"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 3600
  /characters/{character_id}/titles/:
    get:
      tags:
      - "Character"
      summary: "Get character corporation titles"
      description: "Returns a character's titles\n\n---\nAlternate route: `/dev/characters/{character_id}/titles/`\n\
        \n---\nThis route is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_titles"
      security:
      - evesso:
        - "esi-characters.read_titles.v1"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 3600
  /characters/{character_id}/wallet/:
    get:
      tags:
      - "Wallet"
      summary: "Get a character's wallet balance"
      description: "Returns a character's wallet balance\n\n---\nAlternate route:\
        \ `/dev/characters/{character_id}/wallet/`\n\nAlternate route: `/latest/characters/{character_id}/wallet/`\n\
        \nAlternate route: `/legacy/characters/{character_id}/wallet/`\n\nAlternate\
        \ route: `/v1/characters/{character_id}/wallet/`\n\n---\nThis route is cached\
        \ for up to 120 seconds"
      operationId: "get_characters_character_id_wallet"
      security:
      - evesso:
        - "esi-wallet.read_character_wallet.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v1"
      x-cached-seconds: 120
  /characters/{character_id}/wallet/transactions/:
    get:
      tags:
      - "Wallet"
      summary: "Get wallet transactions"
      description: "Get wallet transactions of a character going 30 days back\n\n\
        ---\nAlternate route: `/dev/characters/{character_id}/wallet/transactions/`\n\
        \nAlternate route: `/latest/characters/{character_id}/wallet/transactions/`\n\
        \nAlternate route: `/legacy/characters/{character_id}/wallet/transactions/`\n\
        \nAlternate route: `/v1/characters/{character_id}/wallet/transactions/`\n\n\
        ---\nThis route is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_wallet_transactions"
      security:
      - evesso:
        - "esi-wallet.read_character_wallet.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /corporations/npccorps/:
    get:
      tags:
      - "Corporation"
      summary: "Get npc corporations"
      description: "Get a list of npc corporations\n\n---\nAlternate route: `/dev/corporations/npccorps/`\n\
        \n---\nThis route expires daily at 11:05"
      operationId: "get_corporations_npccorps"
      x-alternate-versions:
      - "dev"
  /corporations/{corporation_id}/alliancehistory/:
    get:
      tags:
      - "Corporation"
      summary: "Get alliance history"
      description: "Get a list of all the alliances a corporation has been a member\
        \ of\n\n---\nAlternate route: `/latest/corporations/{corporation_id}/alliancehistory/`\n\
        \n---\nThis route is cached for up to 3600 seconds"
      operationId: "get_corporations_corporation_id_alliancehistory"
      x-alternate-versions:
      - "latest"
      x-cached-seconds: 3600
  /corporations/{corporation_id}/assets/locations/:
    post:
      tags:
      - "Assets"
      summary: "Get corporation asset locations"
      description: "Return locations for a set of item ids, which you can get from\
        \ corporation assets endpoint. Coordinates for items in hangars or stations\
        \ are set to (0,0,0)\n\n---\nAlternate route: `/dev/corporations/{corporation_id}/assets/locations/`\n\
        \nAlternate route: `/latest/corporations/{corporation_id}/assets/locations/`\n\
        \n\n---\nRequires one of the following EVE corporation role(s): Director\n"
      operationId: "post_corporations_corporation_id_assets_locations"
      security:
      - evesso:
        - "esi-assets.read_corporation_assets.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-required-roles:
      - "Director"
  /corporations/{corporation_id}/blueprints/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation blueprints"
      description: "Returns a list of blueprints the corporation owns\n\n---\nAlternate\
        \ route: `/latest/corporations/{corporation_id}/blueprints/`\n\n---\nThis\
        \ route is cached for up to 3600 seconds\n\n---\nRequires one of the following\
        \ EVE corporation role(s): Director\n"
      operationId: "get_corporations_corporation_id_blueprints"
      security:
      - evesso:
        - "esi-corporations.read_blueprints.v1"
      x-alternate-versions:
      - "latest"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /corporations/{corporation_id}/contacts/:
    get:
      tags:
      - "Contacts"
      summary: "Get corporation contacts"
      description: "Return contacts of a corporation\n\n---\nAlternate route: `/dev/corporations/{corporation_id}/contacts/`\n\
        \nAlternate route: `/latest/corporations/{corporation_id}/contacts/`\n\n---\n\
        This route is cached for up to 300 seconds"
      operationId: "get_corporations_corporation_id_contacts"
      security:
      - evesso:
        - "esi-corporations.read_contacts.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 300
      x-required-roles: []
  /corporations/{corporation_id}/containers/logs/:
    get:
      tags:
      - "Corporation"
      summary: "Get all corporation ALSC logs"
      description: "Returns logs recorded in the past seven days from all audit log\
        \ secure containers (ALSC) owned by a given corporation\n\n---\nAlternate\
        \ route: `/latest/corporations/{corporation_id}/containers/logs/`\n\n---\n\
        This route is cached for up to 600 seconds\n\n---\nRequires one of the following\
        \ EVE corporation role(s): Director\n"
      operationId: "get_corporations_corporation_id_containers_logs"
      security:
      - evesso:
        - "esi-corporations.read_container_logs.v1"
      x-alternate-versions:
      - "latest"
      x-cached-seconds: 600
      x-required-roles:
      - "Director"
  /corporations/{corporation_id}/divisions/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation divisions"
      description: "Return corporation hangar and wallet division names, only show\
        \ if a division is not using the default name\n\n---\nAlternate route: `/dev/corporations/{corporation_id}/divisions/`\n\
        \n---\nThis route is cached for up to 3600 seconds\n\n---\nRequires one of\
        \ the following EVE corporation role(s): Director\n"
      operationId: "get_corporations_corporation_id_divisions"
      security:
      - evesso:
        - "esi-corporations.read_divisions.v1"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /corporations/{corporation_id}/facilities/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation facilities"
      description: "Return a corporation's facilities\n\n---\nAlternate route: `/dev/corporations/{corporation_id}/facilities/`\n\
        \n---\nThis route is cached for up to 3600 seconds\n\n---\nRequires one of\
        \ the following EVE corporation role(s): Factory_Manager\n"
      operationId: "get_corporations_corporation_id_facilities"
      security:
      - evesso:
        - "esi-corporations.read_facilities.v1"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 3600
      x-required-roles:
      - "Factory_Manager"
  /corporations/{corporation_id}/fw/stats/:
    get:
      tags:
      - "Faction Warfare"
      summary: "Overview of a corporation involved in faction warfare"
      description: "Statistics about a corporation involved in faction warfare\n\n\
        ---\nAlternate route: `/dev/corporations/{corporation_id}/fw/stats/`\n\nAlternate\
        \ route: `/latest/corporations/{corporation_id}/fw/stats/`\n\nAlternate route:\
        \ `/legacy/corporations/{corporation_id}/fw/stats/`\n\nAlternate route: `/v1/corporations/{corporation_id}/fw/stats/`\n\
        \n---\nThis route expires daily at 11:05"
      operationId: "get_corporations_corporation_id_fw_stats"
      security:
      - evesso:
        - "esi-corporations.read_fw_stats.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v1"
  /corporations/{corporation_id}/icons/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation icon"
      description: "Get the icon urls for a corporation\n\n---\nAlternate route: `/dev/corporations/{corporation_id}/icons/`\n\
        \n---\nThis route is cached for up to 3600 seconds"
      operationId: "get_corporations_corporation_id_icons"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 3600
  /corporations/{corporation_id}/medals/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation medals"
      description: "Returns a corporation's medals\n\n---\nAlternate route: `/dev/corporations/{corporation_id}/medals/`\n\
        \n---\nThis route is cached for up to 3600 seconds"
      operationId: "get_corporations_corporation_id_medals"
      security:
      - evesso:
        - "esi-corporations.read_medals.v1"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 3600
      x-required-roles: []
  /corporations/{corporation_id}/medals/issued/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation issued medals"
      description: "Returns medals issued by a corporation\n\n---\nAlternate route:\
        \ `/dev/corporations/{corporation_id}/medals/issued/`\n\n---\nThis route is\
        \ cached for up to 3600 seconds\n\n---\nRequires one of the following EVE\
        \ corporation role(s): Director\n"
      operationId: "get_corporations_corporation_id_medals_issued"
      security:
      - evesso:
        - "esi-corporations.read_medals.v1"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /corporations/{corporation_id}/members/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation members"
      description: "Read the current list of members if the calling character is a\
        \ member.\n\n---\nAlternate route: `/legacy/corporations/{corporation_id}/members/`\n\
        \n---\nThis route is cached for up to 3600 seconds\n\n---\nWarning: This route\
        \ is deprecated\n\n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/v2/dev/#GET-/corporations/{corporation_id}/members/)"
      operationId: "get_corporations_corporation_id_members"
      security:
      - evesso:
        - "esi-corporations.read_corporation_membership.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
      x-cached-seconds: 3600
  /corporations/{corporation_id}/members/limit/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation member limit"
      description: "Return a corporation's member limit, not including CEO himself\n\
        \n---\nAlternate route: `/dev/corporations/{corporation_id}/members/limit/`\n\
        \n---\nThis route is cached for up to 3600 seconds\n\n---\nRequires one of\
        \ the following EVE corporation role(s): Director\n"
      operationId: "get_corporations_corporation_id_members_limit"
      security:
      - evesso:
        - "esi-corporations.track_members.v1"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /corporations/{corporation_id}/members/titles/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation's members' titles"
      description: "Returns a corporation's members' titles\n\n---\nAlternate route:\
        \ `/dev/corporations/{corporation_id}/members/titles/`\n\n---\nThis route\
        \ is cached for up to 3600 seconds\n\n---\nRequires one of the following EVE\
        \ corporation role(s): Director\n"
      operationId: "get_corporations_corporation_id_members_titles"
      security:
      - evesso:
        - "esi-corporations.read_titles.v1"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /corporations/{corporation_id}/membertracking/:
    get:
      tags:
      - "Corporation"
      summary: "Track corporation members"
      description: "Returns additional information about a corporation's members which\
        \ helps tracking their activities\n\n---\nAlternate route: `/dev/corporations/{corporation_id}/membertracking/`\n\
        \n---\nThis route is cached for up to 3600 seconds\n\n---\nRequires one of\
        \ the following EVE corporation role(s): Director\n"
      operationId: "get_corporations_corporation_id_membertracking"
      security:
      - evesso:
        - "esi-corporations.track_members.v1"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /corporations/{corporation_id}/orders/:
    get:
      tags:
      - "Market"
      summary: "List open orders from a corporation"
      description: "List open market orders placed on behalf of a corporation\n\n\
        ---\nAlternate route: `/legacy/corporations/{corporation_id}/orders/`\n\n\
        ---\nThis route is cached for up to 1200 seconds\n\n---\nRequires one of the\
        \ following EVE corporation role(s): Accountant, Trader\n\n\n---\nWarning:\
        \ This route is deprecated\n\n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/v2/dev/#GET-/corporations/{corporation_id}/orders/)"
      operationId: "get_corporations_corporation_id_orders"
      security:
      - evesso:
        - "esi-markets.read_corporation_orders.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
      x-cached-seconds: 1200
      x-required-roles:
      - "Accountant"
      - "Trader"
  /corporations/{corporation_id}/orders/history/:
    get:
      tags:
      - "Market"
      summary: "List historical orders from a corporation"
      description: "List cancelled and expired market orders placed on behalf of a\
        \ corporation up to 90 days in the past.\n\n---\nAlternate route: `/dev/corporations/{corporation_id}/orders/history/`\n\
        \nAlternate route: `/latest/corporations/{corporation_id}/orders/history/`\n\
        \n---\nThis route is cached for up to 3600 seconds\n\n---\nRequires one of\
        \ the following EVE corporation role(s): Accountant, Trader\n"
      operationId: "get_corporations_corporation_id_orders_history"
      security:
      - evesso:
        - "esi-markets.read_corporation_orders.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
      x-required-roles:
      - "Accountant"
      - "Trader"
  /corporations/{corporation_id}/roles/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation member roles"
      description: "Return the roles of all members if the character has the personnel\
        \ manager role or any grantable role.\n\n---\nAlternate route: `/dev/corporations/{corporation_id}/roles/`\n\
        \n---\nThis route is cached for up to 3600 seconds"
      operationId: "get_corporations_corporation_id_roles"
      security:
      - evesso:
        - "esi-corporations.read_corporation_membership.v1"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 3600
  /corporations/{corporation_id}/roles/history/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation member roles history"
      description: "Return how roles have changed for a coporation's members, up to\
        \ a month\n\n---\nAlternate route: `/dev/corporations/{corporation_id}/roles/history/`\n\
        \n---\nThis route is cached for up to 3600 seconds\n\n---\nRequires one of\
        \ the following EVE corporation role(s): Director\n"
      operationId: "get_corporations_corporation_id_roles_history"
      security:
      - evesso:
        - "esi-corporations.read_corporation_membership.v1"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /corporations/{corporation_id}/standings/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation standings"
      description: "Return corporation standings from agents, NPC corporations, and\
        \ factions\n\n---\nAlternate route: `/dev/corporations/{corporation_id}/standings/`\n\
        \n---\nThis route is cached for up to 3600 seconds"
      operationId: "get_corporations_corporation_id_standings"
      security:
      - evesso:
        - "esi-corporations.read_standings.v1"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 3600
      x-required-roles: []
  /corporations/{corporation_id}/starbases/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation starbases (POSes)"
      description: "Returns list of corporation starbases (POSes)\n\n---\nAlternate\
        \ route: `/dev/corporations/{corporation_id}/starbases/`\n\n---\nThis route\
        \ is cached for up to 3600 seconds\n\n---\nRequires one of the following EVE\
        \ corporation role(s): Director\n"
      operationId: "get_corporations_corporation_id_starbases"
      security:
      - evesso:
        - "esi-corporations.read_starbases.v2"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /corporations/{corporation_id}/starbases/{starbase_id}/:
    get:
      tags:
      - "Corporation"
      summary: "Get starbase (POS) detail"
      description: "Returns various settings and fuels of a starbase (POS)\n\n---\n\
        Alternate route: `/dev/corporations/{corporation_id}/starbases/{starbase_id}/`\n\
        \n---\nThis route is cached for up to 3600 seconds\n\n---\nRequires one of\
        \ the following EVE corporation role(s): Director\n"
      operationId: "get_corporations_corporation_id_starbases_starbase_id"
      security:
      - evesso:
        - "esi-corporations.read_starbases.v1"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /corporations/{corporation_id}/structures/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation structures"
      description: "Get a list of corporation structures. This route's version includes\
        \ the changes to structures detailed in this blog: https://www.eveonline.com/article/upwell-2.0-structures-changes-coming-on-february-13th\
        \ Note: this route will not return any flex structures owned by a corporation,\
        \ use the v3 route to have those included in the response. A list of FLEX\
        \ structures can be found here: https://support.eveonline.com/hc/en-us/articles/213021829-Upwell-Structures\n\
        \n---\nAlternate route: `/legacy/corporations/{corporation_id}/structures/`\n\
        \n---\nThis route is cached for up to 3600 seconds\n\n---\nRequires one of\
        \ the following EVE corporation role(s): Station_Manager\n\n\n---\nWarning:\
        \ This route is deprecated\n\n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/v2/dev/#GET-/corporations/{corporation_id}/structures/)"
      operationId: "get_corporations_corporation_id_structures"
      security:
      - evesso:
        - "esi-corporations.read_structures.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
      x-cached-seconds: 3600
      x-required-roles:
      - "Station_Manager"
  /corporations/{corporation_id}/titles/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation titles"
      description: "Returns a corporation's titles\n\n---\nAlternate route: `/dev/corporations/{corporation_id}/titles/`\n\
        \n---\nThis route is cached for up to 3600 seconds\n\n---\nRequires one of\
        \ the following EVE corporation role(s): Director\n"
      operationId: "get_corporations_corporation_id_titles"
      security:
      - evesso:
        - "esi-corporations.read_titles.v1"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /corporations/{corporation_id}/wallets/{division}/transactions/:
    get:
      tags:
      - "Wallet"
      summary: "Get corporation wallet transactions"
      description: "Get wallet transactions of a corporation going 30 days back\n\n\
        ---\nAlternate route: `/dev/corporations/{corporation_id}/wallets/{division}/transactions/`\n\
        \nAlternate route: `/latest/corporations/{corporation_id}/wallets/{division}/transactions/`\n\
        \nAlternate route: `/legacy/corporations/{corporation_id}/wallets/{division}/transactions/`\n\
        \nAlternate route: `/v1/corporations/{corporation_id}/wallets/{division}/transactions/`\n\
        \n---\nThis route is cached for up to 3600 seconds\n\n---\nRequires one of\
        \ the following EVE corporation role(s): Accountant, Junior_Accountant\n"
      operationId: "get_corporations_corporation_id_wallets_division_transactions"
      security:
      - evesso:
        - "esi-wallet.read_corporation_wallets.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
      x-required-roles:
      - "Accountant"
      - "Junior_Accountant"
  /dogma/effects/{effect_id}/:
    get:
      tags:
      - "Dogma"
      summary: "Get effect information"
      description: "Get information on a dogma effect\n\n---\nAlternate route: `/dev/dogma/effects/{effect_id}/`\n\
        \nAlternate route: `/latest/dogma/effects/{effect_id}/`\n\n---\nThis route\
        \ expires daily at 11:05"
      operationId: "get_dogma_effects_effect_id"
      x-alternate-versions:
      - "dev"
      - "latest"
  /fw/leaderboards/:
    get:
      tags:
      - "Faction Warfare"
      summary: "List of the top factions in faction warfare"
      description: "Top 4 leaderboard of factions for kills and victory points separated\
        \ by total, last week and yesterday\n\n---\nAlternate route: `/dev/fw/leaderboards/`\n\
        \nAlternate route: `/latest/fw/leaderboards/`\n\nAlternate route: `/legacy/fw/leaderboards/`\n\
        \nAlternate route: `/v1/fw/leaderboards/`\n\n---\nThis route expires daily\
        \ at 11:05"
      operationId: "get_fw_leaderboards"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v1"
  /fw/leaderboards/characters/:
    get:
      tags:
      - "Faction Warfare"
      summary: "List of the top pilots in faction warfare"
      description: "Top 100 leaderboard of pilots for kills and victory points separated\
        \ by total, last week and yesterday\n\n---\nAlternate route: `/dev/fw/leaderboards/characters/`\n\
        \nAlternate route: `/latest/fw/leaderboards/characters/`\n\nAlternate route:\
        \ `/legacy/fw/leaderboards/characters/`\n\nAlternate route: `/v1/fw/leaderboards/characters/`\n\
        \n---\nThis route expires daily at 11:05"
      operationId: "get_fw_leaderboards_characters"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v1"
  /fw/leaderboards/corporations/:
    get:
      tags:
      - "Faction Warfare"
      summary: "List of the top corporations in faction warfare"
      description: "Top 10 leaderboard of corporations for kills and victory points\
        \ separated by total, last week and yesterday\n\n---\nAlternate route: `/dev/fw/leaderboards/corporations/`\n\
        \nAlternate route: `/latest/fw/leaderboards/corporations/`\n\nAlternate route:\
        \ `/legacy/fw/leaderboards/corporations/`\n\nAlternate route: `/v1/fw/leaderboards/corporations/`\n\
        \n---\nThis route expires daily at 11:05"
      operationId: "get_fw_leaderboards_corporations"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v1"
  /fw/stats/:
    get:
      tags:
      - "Faction Warfare"
      summary: "An overview of statistics about factions involved in faction warfare"
      description: "Statistical overviews of factions involved in faction warfare\n\
        \n---\nAlternate route: `/dev/fw/stats/`\n\nAlternate route: `/latest/fw/stats/`\n\
        \nAlternate route: `/legacy/fw/stats/`\n\nAlternate route: `/v1/fw/stats/`\n\
        \n---\nThis route expires daily at 11:05"
      operationId: "get_fw_stats"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v1"
  /fw/systems/:
    get:
      tags:
      - "Faction Warfare"
      summary: "Ownership of faction warfare systems"
      description: "An overview of the current ownership of faction warfare solar\
        \ systems\n\n---\nAlternate route: `/dev/fw/systems/`\n\nAlternate route:\
        \ `/latest/fw/systems/`\n\nAlternate route: `/legacy/fw/systems/`\n\nAlternate\
        \ route: `/v3/fw/systems/`\n\n---\nThis route is cached for up to 1800 seconds"
      operationId: "get_fw_systems"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v3"
      x-cached-seconds: 1800
  /fw/wars/:
    get:
      tags:
      - "Faction Warfare"
      summary: "Data about which NPC factions are at war"
      description: "Data about which NPC factions are at war\n\n---\nAlternate route:\
        \ `/dev/fw/wars/`\n\nAlternate route: `/latest/fw/wars/`\n\nAlternate route:\
        \ `/legacy/fw/wars/`\n\nAlternate route: `/v1/fw/wars/`\n\n---\nThis route\
        \ expires daily at 11:05"
      operationId: "get_fw_wars"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v1"
  /search/:
    get:
      tags:
      - "Search"
      summary: "Search on a string"
      description: "Search for entities that match a given sub-string.\n\n---\nAlternate\
        \ route: `/dev/search/`\n\nAlternate route: `/latest/search/`\n\nAlternate\
        \ route: `/legacy/search/`\n\n---\nThis route is cached for up to 3600 seconds"
      operationId: "get_search"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      x-cached-seconds: 3600
  /status/:
    get:
      tags:
      - "Status"
      summary: "Retrieve the uptime and player counts"
      description: "EVE Server status\n\n---\nAlternate route: `/dev/status/`\n\n\
        Alternate route: `/latest/status/`\n\nAlternate route: `/legacy/status/`\n\
        \nAlternate route: `/v1/status/`\n\n---\nThis route is cached for up to 30\
        \ seconds"
      operationId: "get_status"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v1"
      x-cached-seconds: 30
  /ui/autopilot/waypoint/:
    post:
      tags:
      - "User Interface"
      summary: "Set Autopilot Waypoint"
      description: "Set a solar system as autopilot waypoint\n\n---\nAlternate route:\
        \ `/dev/ui/autopilot/waypoint/`\n\nAlternate route: `/latest/ui/autopilot/waypoint/`\n\
        \nAlternate route: `/legacy/ui/autopilot/waypoint/`\n"
      operationId: "post_ui_autopilot_waypoint"
      security:
      - evesso:
        - "esi-ui.write_waypoint.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
  /universe/ancestries/:
    get:
      tags:
      - "Universe"
      summary: "Get ancestries"
      description: "Get all character ancestries\n\n---\nAlternate route: `/dev/universe/ancestries/`\n\
        \n---\nThis route expires daily at 11:05"
      operationId: "get_universe_ancestries"
      x-alternate-versions:
      - "dev"
  /universe/asteroid_belts/{asteroid_belt_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get asteroid belt information"
      description: "Get information on an asteroid belt\n\n---\nAlternate route: `/dev/universe/asteroid_belts/{asteroid_belt_id}/`\n\
        \n---\nThis route expires daily at 11:05"
      operationId: "get_universe_asteroid_belts_asteroid_belt_id"
      x-alternate-versions:
      - "dev"
  /universe/bloodlines/:
    get:
      tags:
      - "Universe"
      summary: "Get bloodlines"
      description: "Get a list of bloodlines\n\n---\nAlternate route: `/dev/universe/bloodlines/`\n\
        \n---\nThis route expires daily at 11:05"
      operationId: "get_universe_bloodlines"
      x-alternate-versions:
      - "dev"
  /universe/categories/:
    get:
      tags:
      - "Universe"
      summary: "Get item categories"
      description: "Get a list of item categories\n\n---\nAlternate route: `/dev/universe/categories/`\n\
        \n---\nThis route expires daily at 11:05"
      operationId: "get_universe_categories"
      x-alternate-versions:
      - "dev"
  /universe/categories/{category_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get item category information"
      description: "Get information of an item category\n\n---\nAlternate route: `/dev/universe/categories/{category_id}/`\n\
        \n---\nThis route expires daily at 11:05"
      operationId: "get_universe_categories_category_id"
      x-alternate-versions:
      - "dev"
  /universe/constellations/:
    get:
      tags:
      - "Universe"
      summary: "Get constellations"
      description: "Get a list of constellations\n\n---\nAlternate route: `/dev/universe/constellations/`\n\
        \n---\nThis route expires daily at 11:05"
      operationId: "get_universe_constellations"
      x-alternate-versions:
      - "dev"
  /universe/constellations/{constellation_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get constellation information"
      description: "Get information on a constellation\n\n---\nAlternate route: `/dev/universe/constellations/{constellation_id}/`\n\
        \n---\nThis route expires daily at 11:05"
      operationId: "get_universe_constellations_constellation_id"
      x-alternate-versions:
      - "dev"
  /universe/factions/:
    get:
      tags:
      - "Universe"
      summary: "Get factions"
      description: "Get a list of factions\n\n---\nAlternate route: `/dev/universe/factions/`\n\
        \nAlternate route: `/latest/universe/factions/`\n\n---\nThis route expires\
        \ daily at 11:05"
      operationId: "get_universe_factions"
      x-alternate-versions:
      - "dev"
      - "latest"
  /universe/graphics/:
    get:
      tags:
      - "Universe"
      summary: "Get graphics"
      description: "Get a list of graphics\n\n---\nAlternate route: `/dev/universe/graphics/`\n\
        \n---\nThis route expires daily at 11:05"
      operationId: "get_universe_graphics"
      x-alternate-versions:
      - "dev"
  /universe/groups/:
    get:
      tags:
      - "Universe"
      summary: "Get item groups"
      description: "Get a list of item groups\n\n---\nAlternate route: `/dev/universe/groups/`\n\
        \n---\nThis route expires daily at 11:05"
      operationId: "get_universe_groups"
      x-alternate-versions:
      - "dev"
  /universe/moons/{moon_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get moon information"
      description: "Get information on a moon\n\n---\nAlternate route: `/dev/universe/moons/{moon_id}/`\n\
        \n---\nThis route expires daily at 11:05"
      operationId: "get_universe_moons_moon_id"
      x-alternate-versions:
      - "dev"
  /universe/names/:
    post:
      tags:
      - "Universe"
      summary: "Get names and categories for a set of IDs"
      description: "Resolve a set of IDs to names and categories. Supported ID's for\
        \ resolving are: Characters, Corporations, Alliances, Stations, Solar Systems,\
        \ Constellations, Regions, Types\n\n---\nAlternate route: `/legacy/universe/names/`\n\
        \n\n---\nWarning: This route is deprecated\n\n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/v2/dev/#POST-/universe/names/)"
      operationId: "post_universe_names"
      deprecated: true
      x-alternate-versions:
      - "legacy"
  /universe/planets/{planet_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get planet information"
      description: "Get information on a planet\n\n---\nAlternate route: `/dev/universe/planets/{planet_id}/`\n\
        \n---\nThis route expires daily at 11:05"
      operationId: "get_universe_planets_planet_id"
      x-alternate-versions:
      - "dev"
  /universe/regions/:
    get:
      tags:
      - "Universe"
      summary: "Get regions"
      description: "Get a list of regions\n\n---\nAlternate route: `/dev/universe/regions/`\n\
        \n---\nThis route expires daily at 11:05"
      operationId: "get_universe_regions"
      x-alternate-versions:
      - "dev"
  /universe/regions/{region_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get region information"
      description: "Get information on a region\n\n---\nAlternate route: `/dev/universe/regions/{region_id}/`\n\
        \n---\nThis route expires daily at 11:05"
      operationId: "get_universe_regions_region_id"
      x-alternate-versions:
      - "dev"
  /universe/stargates/{stargate_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get stargate information"
      description: "Get information on a stargate\n\n---\nAlternate route: `/dev/universe/stargates/{stargate_id}/`\n\
        \n---\nThis route expires daily at 11:05"
      operationId: "get_universe_stargates_stargate_id"
      x-alternate-versions:
      - "dev"
  /universe/stars/{star_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get star information"
      description: "Get information on a star\n\n---\nAlternate route: `/dev/universe/stars/{star_id}/`\n\
        \n---\nThis route expires daily at 11:05"
      operationId: "get_universe_stars_star_id"
      x-alternate-versions:
      - "dev"
  /universe/stations/{station_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get station information"
      description: "Get information on a station\n\n---\nAlternate route: `/dev/universe/stations/{station_id}/`\n\
        \nAlternate route: `/latest/universe/stations/{station_id}/`\n\n---\nThis\
        \ route expires daily at 11:05"
      operationId: "get_universe_stations_station_id"
      x-alternate-versions:
      - "dev"
      - "latest"
  /universe/structures/{structure_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get structure information"
      description: "Returns information on requested structure if you are on the ACL.\
        \ Otherwise, returns \"Forbidden\" for all inputs.\n\n---\nAlternate route:\
        \ `/latest/universe/structures/{structure_id}/`\n\n---\nThis route is cached\
        \ for up to 3600 seconds"
      operationId: "get_universe_structures_structure_id"
      security:
      - evesso:
        - "esi-universe.read_structures.v1"
      x-alternate-versions:
      - "latest"
      x-cached-seconds: 3600
  /universe/system_jumps/:
    get:
      tags:
      - "Universe"
      summary: "Get system jumps"
      description: "Get the number of jumps in solar systems within the last hour\
        \ ending at the timestamp of the Last-Modified header, excluding wormhole\
        \ space. Only systems with jumps will be listed\n\n---\nAlternate route: `/dev/universe/system_jumps/`\n\
        \n---\nThis route is cached for up to 3600 seconds"
      operationId: "get_universe_system_jumps"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 3600
  /universe/system_kills/:
    get:
      tags:
      - "Universe"
      summary: "Get system kills"
      description: "Get the number of ship, pod and NPC kills per solar system within\
        \ the last hour ending at the timestamp of the Last-Modified header, excluding\
        \ wormhole space. Only systems with kills will be listed\n\n---\nAlternate\
        \ route: `/latest/universe/system_kills/`\n\n---\nThis route is cached for\
        \ up to 3600 seconds"
      operationId: "get_universe_system_kills"
      x-alternate-versions:
      - "latest"
      x-cached-seconds: 3600
  /universe/types/:
    get:
      tags:
      - "Universe"
      summary: "Get types"
      description: "Get a list of type ids\n\n---\nAlternate route: `/dev/universe/types/`\n\
        \n---\nThis route expires daily at 11:05"
      operationId: "get_universe_types"
      x-alternate-versions:
      - "dev"
  /universe/types/{type_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get type information"
      description: "Get information on a type\n\n---\nAlternate route: `/legacy/universe/types/{type_id}/`\n\
        \n---\nThis route expires daily at 11:05\n\n---\nWarning: This route is deprecated\n\
        \n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/v2/dev/#GET-/universe/types/{type_id}/)"
      operationId: "get_universe_types_type_id"
      deprecated: true
      x-alternate-versions:
      - "legacy"
securityDefinitions:
  evesso:
    type: "oauth2"
    authorizationUrl: "https://login.eveonline.com/v2/oauth/authorize"
    flow: "implicit"
    scopes:
      esi-alliances.read_contacts.v1: "EVE SSO scope esi-alliances.read_contacts.v1"
      esi-assets.read_assets.v1: "EVE SSO scope esi-assets.read_assets.v1"
      esi-assets.read_corporation_assets.v1: "EVE SSO scope esi-assets.read_corporation_assets.v1"
      esi-bookmarks.read_character_bookmarks.v1: "EVE SSO scope esi-bookmarks.read_character_bookmarks.v1"
      esi-calendar.read_calendar_events.v1: "EVE SSO scope esi-calendar.read_calendar_events.v1"
      esi-characters.read_agents_research.v1: "EVE SSO scope esi-characters.read_agents_research.v1"
      esi-characters.read_blueprints.v1: "EVE SSO scope esi-characters.read_blueprints.v1"
      esi-characters.read_contacts.v1: "EVE SSO scope esi-characters.read_contacts.v1"
      esi-characters.read_corporation_roles.v1: "EVE SSO scope esi-characters.read_corporation_roles.v1"
      esi-characters.read_fatigue.v1: "EVE SSO scope esi-characters.read_fatigue.v1"
      esi-characters.read_fw_stats.v1: "EVE SSO scope esi-characters.read_fw_stats.v1"
      esi-characters.read_medals.v1: "EVE SSO scope esi-characters.read_medals.v1"
      esi-characters.read_notifications.v1: "EVE SSO scope esi-characters.read_notifications.v1"
      esi-characters.read_standings.v1: "EVE SSO scope esi-characters.read_standings.v1"
      esi-characters.read_titles.v1: "EVE SSO scope esi-characters.read_titles.v1"
      esi-characters.write_contacts.v1: "EVE SSO scope esi-characters.write_contacts.v1"
      esi-clones.read_clones.v1: "EVE SSO scope esi-clones.read_clones.v1"
      esi-clones.read_implants.v1: "EVE SSO scope esi-clones.read_implants.v1"
      esi-corporations.read_blueprints.v1: "EVE SSO scope esi-corporations.read_blueprints.v1"
      esi-corporations.read_contacts.v1: "EVE SSO scope esi-corporations.read_contacts.v1"
      esi-corporations.read_container_logs.v1: "EVE SSO scope esi-corporations.read_container_logs.v1"
      esi-corporations.read_corporation_membership.v1: "EVE SSO scope esi-corporations.read_corporation_membership.v1"
      esi-corporations.read_divisions.v1: "EVE SSO scope esi-corporations.read_divisions.v1"
      esi-corporations.read_facilities.v1: "EVE SSO scope esi-corporations.read_facilities.v1"
      esi-corporations.read_fw_stats.v1: "EVE SSO scope esi-corporations.read_fw_stats.v1"
      esi-corporations.read_medals.v1: "EVE SSO scope esi-corporations.read_medals.v1"
      esi-corporations.read_standings.v1: "EVE SSO scope esi-corporations.read_standings.v1"
      esi-corporations.read_starbases.v1: "EVE SSO scope esi-corporations.read_starbases.v1"
      esi-corporations.read_starbases.v2: "EVE SSO scope esi-corporations.read_starbases.v2"
      esi-corporations.read_structures.v1: "EVE SSO scope esi-corporations.read_structures.v1"
      esi-corporations.read_titles.v1: "EVE SSO scope esi-corporations.read_titles.v1"
      esi-corporations.track_members.v1: "EVE SSO scope esi-corporations.track_members.v1"
      esi-fittings.read_fittings.v1: "EVE SSO scope esi-fittings.read_fittings.v1"
      esi-fittings.write_fittings.v1: "EVE SSO scope esi-fittings.write_fittings.v1"
      esi-fleets.read_fleet.v1: "EVE SSO scope esi-fleets.read_fleet.v1"
      esi-location.read_location.v1: "EVE SSO scope esi-location.read_location.v1"
      esi-location.read_online.v1: "EVE SSO scope esi-location.read_online.v1"
      esi-location.read_ship_type.v1: "EVE SSO scope esi-location.read_ship_type.v1"
      esi-mail.organize_mail.v1: "EVE SSO scope esi-mail.organize_mail.v1"
      esi-mail.read_mail.v1: "EVE SSO scope esi-mail.read_mail.v1"
      esi-markets.read_character_orders.v1: "EVE SSO scope esi-markets.read_character_orders.v1"
      esi-markets.read_corporation_orders.v1: "EVE SSO scope esi-markets.read_corporation_orders.v1"
      esi-skills.read_skillqueue.v1: "EVE SSO scope esi-skills.read_skillqueue.v1"
      esi-ui.write_waypoint.v1: "EVE SSO scope esi-ui.write_waypoint.v1"
      esi-universe.read_structures.v1: "EVE SSO scope esi-universe.read_structures.v1"
      esi-wallet.read_character_wallet.v1: "EVE SSO scope esi-wallet.read_character_wallet.v1"
      esi-wallet.read_corporation_wallets.v1: "EVE SSO scope esi-wallet.read_corporation_wallets.v1"