---
swagger: "2.0"
info:
  description: "An OpenAPI for EVE Online"
  version: "0.8.4"
  title: "EVE Swagger Interface"
host: "esi.evetech.net"
basePath: "/v2"
schemes:
- "https"
paths:
  /alliances/{alliance_id}/:
    get:
      tags:
      - "Alliance"
      summary: "Get alliance information"
      description: "Public information about an alliance\n\n---\nAlternate route:\
        \ `/legacy/alliances/{alliance_id}/`\n\n---\nThis route is cached for up to\
        \ 3600 seconds\n\n---\nWarning: This route is deprecated.\n\n---\n[Diff of\
        \ the upcoming changes](https://esi.evetech.net/diff/v2/dev/#GET-/alliances/{alliance_id}/)"
      operationId: "get_alliances_alliance_id"
      deprecated: true
      x-alternate-versions:
      - "legacy"
      x-cached-seconds: 3600
  /alliances/{alliance_id}/contacts/:
    get:
      tags:
      - "Contacts"
      summary: "Get alliance contacts"
      description: "Return contacts of an alliance\n\n---\nAlternate route: `/dev/alliances/{alliance_id}/contacts/`\n\
        \nAlternate route: `/latest/alliances/{alliance_id}/contacts/`\n\n---\nThis\
        \ route is cached for up to 300 seconds"
      operationId: "get_alliances_alliance_id_contacts"
      security:
      - evesso:
        - "esi-alliances.read_contacts.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 300
  /characters/{character_id}/assets/:
    get:
      tags:
      - "Assets"
      summary: "Get character assets"
      description: "Return a list of the characters assets\n\n---\nAlternate route:\
        \ `/legacy/characters/{character_id}/assets/`\n\n---\nThis route is cached\
        \ for up to 3600 seconds\n\n---\nWarning: This route is deprecated.\n\n---\n\
        [Diff of the upcoming changes](https://esi.evetech.net/diff/v2/dev/#GET-/characters/{character_id}/assets/)"
      operationId: "get_characters_character_id_assets"
      security:
      - evesso:
        - "esi-assets.read_assets.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
      x-cached-seconds: 3600
  /characters/{character_id}/assets/locations/:
    post:
      tags:
      - "Assets"
      summary: "Get character asset locations"
      description: "Return locations for a set of item ids, which you can get from\
        \ character assets endpoint. Coordinates for items in hangars or stations\
        \ are set to (0,0,0)\n\n---\nAlternate route: `/dev/characters/{character_id}/assets/locations/`\n\
        \nAlternate route: `/latest/characters/{character_id}/assets/locations/`\n"
      operationId: "post_characters_character_id_assets_locations"
      security:
      - evesso:
        - "esi-assets.read_assets.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
  /characters/{character_id}/blueprints/:
    get:
      tags:
      - "Character"
      summary: "Get blueprints"
      description: "Return a list of blueprints the character owns\n\n---\nAlternate\
        \ route: `/dev/characters/{character_id}/blueprints/`\n\nAlternate route:\
        \ `/latest/characters/{character_id}/blueprints/`\n\n---\nThis route is cached\
        \ for up to 3600 seconds"
      operationId: "get_characters_character_id_blueprints"
      security:
      - evesso:
        - "esi-characters.read_blueprints.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
  /characters/{character_id}/bookmarks/:
    get:
      tags:
      - "Bookmarks"
      summary: "List bookmarks"
      description: "A list of your character's personal bookmarks\n\n---\nAlternate\
        \ route: `/dev/characters/{character_id}/bookmarks/`\n\nAlternate route: `/latest/characters/{character_id}/bookmarks/`\n\
        \n---\nThis route is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_bookmarks"
      security:
      - evesso:
        - "esi-bookmarks.read_character_bookmarks.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
  /characters/{character_id}/bookmarks/folders/:
    get:
      tags:
      - "Bookmarks"
      summary: "List bookmark folders"
      description: "A list of your character's personal bookmark folders\n\n---\n\
        Alternate route: `/dev/characters/{character_id}/bookmarks/folders/`\n\nAlternate\
        \ route: `/latest/characters/{character_id}/bookmarks/folders/`\n\n---\nThis\
        \ route is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_bookmarks_folders"
      security:
      - evesso:
        - "esi-bookmarks.read_character_bookmarks.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
  /characters/{character_id}/calendar/{event_id}/:
    get:
      tags:
      - "Calendar"
      summary: "Get an event"
      description: "Get all the information for a specific event\n\n---\nAlternate\
        \ route: `/legacy/characters/{character_id}/calendar/{event_id}/`\n\n---\n\
        This route is cached for up to 5 seconds\n\n---\nWarning: This route is deprecated.\n\
        \n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/v2/dev/#GET-/characters/{character_id}/calendar/{event_id}/)"
      operationId: "get_characters_character_id_calendar_event_id"
      security:
      - evesso:
        - "esi-calendar.read_calendar_events.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
      x-cached-seconds: 5
    put:
      tags:
      - "Calendar"
      summary: "Respond to an event"
      description: "Set your response status to an event\n\n---\nAlternate route:\
        \ `/legacy/characters/{character_id}/calendar/{event_id}/`\n\n\n---\nWarning:\
        \ This route is deprecated.\n\n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/v2/dev/#PUT-/characters/{character_id}/calendar/{event_id}/)"
      operationId: "put_characters_character_id_calendar_event_id"
      security:
      - evesso:
        - "esi-calendar.respond_calendar_events.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
  /characters/{character_id}/clones/:
    get:
      tags:
      - "Clones"
      summary: "Get clones"
      description: "A list of the character's clones\n\n---\nAlternate route: `/legacy/characters/{character_id}/clones/`\n\
        \n---\nThis route is cached for up to 120 seconds\n\n---\nWarning: This route\
        \ is deprecated.\n\n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/v2/dev/#GET-/characters/{character_id}/clones/)"
      operationId: "get_characters_character_id_clones"
      security:
      - evesso:
        - "esi-clones.read_clones.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
      x-cached-seconds: 120
  /characters/{character_id}/contacts/:
    get:
      tags:
      - "Contacts"
      summary: "Get contacts"
      description: "Return contacts of a character\n\n---\nAlternate route: `/dev/characters/{character_id}/contacts/`\n\
        \nAlternate route: `/latest/characters/{character_id}/contacts/`\n\n---\n\
        This route is cached for up to 300 seconds"
      operationId: "get_characters_character_id_contacts"
      security:
      - evesso:
        - "esi-characters.read_contacts.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 300
    post:
      tags:
      - "Contacts"
      summary: "Add contacts"
      description: "Bulk add contacts with same settings\n\n---\nAlternate route:\
        \ `/dev/characters/{character_id}/contacts/`\n\nAlternate route: `/latest/characters/{character_id}/contacts/`\n"
      operationId: "post_characters_character_id_contacts"
      security:
      - evesso:
        - "esi-characters.write_contacts.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
    put:
      tags:
      - "Contacts"
      summary: "Edit contacts"
      description: "Bulk edit contacts with same settings\n\n---\nAlternate route:\
        \ `/dev/characters/{character_id}/contacts/`\n\nAlternate route: `/latest/characters/{character_id}/contacts/`\n"
      operationId: "put_characters_character_id_contacts"
      security:
      - evesso:
        - "esi-characters.write_contacts.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
    delete:
      tags:
      - "Contacts"
      summary: "Delete contacts"
      description: "Bulk delete contacts\n\n---\nAlternate route: `/dev/characters/{character_id}/contacts/`\n\
        \nAlternate route: `/latest/characters/{character_id}/contacts/`\n"
      operationId: "delete_characters_character_id_contacts"
      security:
      - evesso:
        - "esi-characters.write_contacts.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
  /characters/{character_id}/mail/labels/:
    get:
      tags:
      - "Mail"
      summary: "Get mail labels"
      description: "Return a list of the users mail labels\n\n---\nAlternate route:\
        \ `/legacy/characters/{character_id}/mail/labels/`\n\n---\nThis route is cached\
        \ for up to 30 seconds\n\n---\nWarning: This route is deprecated.\n\n---\n\
        [Diff of the upcoming changes](https://esi.evetech.net/diff/v2/dev/#GET-/characters/{character_id}/mail/labels/)"
      operationId: "get_characters_character_id_mail_labels"
      security:
      - evesso:
        - "esi-mail.read_mail.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
      x-cached-seconds: 30
    post:
      tags:
      - "Mail"
      summary: "Create a mail label"
      description: "Create a mail label\n\n---\nAlternate route: `/dev/characters/{character_id}/mail/labels/`\n\
        \nAlternate route: `/latest/characters/{character_id}/mail/labels/`\n\nAlternate\
        \ route: `/legacy/characters/{character_id}/mail/labels/`\n"
      operationId: "post_characters_character_id_mail_labels"
      security:
      - evesso:
        - "esi-mail.organize_mail.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
  /characters/{character_id}/notifications/:
    get:
      tags:
      - "Character"
      summary: "Get character notifications"
      description: "Return character notifications\n\n---\nAlternate route: `/dev/characters/{character_id}/notifications/`\n\
        \nAlternate route: `/latest/characters/{character_id}/notifications/`\n\n\
        ---\nThis route is cached for up to 600 seconds"
      operationId: "get_characters_character_id_notifications"
      security:
      - evesso:
        - "esi-characters.read_notifications.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 600
  /characters/{character_id}/online/:
    get:
      tags:
      - "Location"
      summary: "Get character online"
      description: "Checks if the character is currently online\n\n---\nAlternate\
        \ route: `/dev/characters/{character_id}/online/`\n\nAlternate route: `/latest/characters/{character_id}/online/`\n\
        \n---\nThis route is cached for up to 60 seconds"
      operationId: "get_characters_character_id_online"
      security:
      - evesso:
        - "esi-location.read_online.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 60
  /characters/{character_id}/orders/:
    get:
      tags:
      - "Market"
      summary: "List open orders from a character"
      description: "List open market orders placed by a character\n\n---\nAlternate\
        \ route: `/dev/characters/{character_id}/orders/`\n\nAlternate route: `/latest/characters/{character_id}/orders/`\n\
        \n---\nThis route is cached for up to 1200 seconds"
      operationId: "get_characters_character_id_orders"
      security:
      - evesso:
        - "esi-markets.read_character_orders.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 1200
  /characters/{character_id}/planets/{planet_id}/:
    get:
      tags:
      - "Planetary Interaction"
      summary: "Get colony layout"
      description: "Returns full details on the layout of a single planetary colony,\
        \ including links, pins and routes. Note: Planetary information is only recalculated\
        \ when the colony is viewed through the client. Information will not update\
        \ until this criteria is met.\n\n---\nAlternate route: `/legacy/characters/{character_id}/planets/{planet_id}/`\n\
        \n---\nThis route is cached for up to 600 seconds\n\n---\nWarning: This route\
        \ is deprecated.\n\n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/v2/dev/#GET-/characters/{character_id}/planets/{planet_id}/)"
      operationId: "get_characters_character_id_planets_planet_id"
      security:
      - evesso:
        - "esi-planets.manage_planets.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
      x-cached-seconds: 600
  /characters/{character_id}/portrait/:
    get:
      tags:
      - "Character"
      summary: "Get character portraits"
      description: "Get portrait urls for a character\n\n---\nAlternate route: `/dev/characters/{character_id}/portrait/`\n\
        \nAlternate route: `/latest/characters/{character_id}/portrait/`\n\n---\n\
        This route is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_portrait"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
  /characters/{character_id}/roles/:
    get:
      tags:
      - "Character"
      summary: "Get character corporation roles"
      description: "Returns a character's corporation roles\n\n---\nAlternate route:\
        \ `/dev/characters/{character_id}/roles/`\n\nAlternate route: `/latest/characters/{character_id}/roles/`\n\
        \n---\nThis route is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_roles"
      security:
      - evesso:
        - "esi-characters.read_corporation_roles.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
  /characters/{character_id}/search/:
    get:
      tags:
      - "Search"
      summary: "Search on a string"
      description: "Search for entities that match a given sub-string.\n\n---\nAlternate\
        \ route: `/legacy/characters/{character_id}/search/`\n\n---\nThis route is\
        \ cached for up to 3600 seconds\n\n---\nWarning: This route is deprecated.\n\
        \n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/v2/dev/#GET-/characters/{character_id}/search/)"
      operationId: "get_characters_character_id_search"
      security:
      - evesso:
        - "esi-search.search_structures.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
      x-cached-seconds: 3600
  /characters/{character_id}/skillqueue/:
    get:
      tags:
      - "Skills"
      summary: "Get character's skill queue"
      description: "List the configured skill queue for the given character\n\n---\n\
        Alternate route: `/dev/characters/{character_id}/skillqueue/`\n\nAlternate\
        \ route: `/latest/characters/{character_id}/skillqueue/`\n\nAlternate route:\
        \ `/legacy/characters/{character_id}/skillqueue/`\n\n---\nThis route is cached\
        \ for up to 120 seconds"
      operationId: "get_characters_character_id_skillqueue"
      security:
      - evesso:
        - "esi-skills.read_skillqueue.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      x-cached-seconds: 120
  /characters/{character_id}/stats/:
    get:
      tags:
      - "Character"
      summary: "Yearly aggregate stats"
      description: "Returns aggregate yearly stats for a character\n\n---\nAlternate\
        \ route: `/dev/characters/{character_id}/stats/`\n\nAlternate route: `/latest/characters/{character_id}/stats/`\n\
        \n---\nThis route is cached for up to 86400 seconds"
      operationId: "get_characters_character_id_stats"
      security:
      - evesso:
        - "esi-characterstats.read.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 86400
  /corporations/{corporation_id}/alliancehistory/:
    get:
      tags:
      - "Corporation"
      summary: "Get alliance history"
      description: "Get a list of all the alliances a corporation has been a member\
        \ of\n\n---\nAlternate route: `/dev/corporations/{corporation_id}/alliancehistory/`\n\
        \nAlternate route: `/latest/corporations/{corporation_id}/alliancehistory/`\n\
        \n---\nThis route is cached for up to 3600 seconds"
      operationId: "get_corporations_corporation_id_alliancehistory"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
  /corporations/{corporation_id}/assets/:
    get:
      tags:
      - "Assets"
      summary: "Get corporation assets"
      description: "Return a list of the corporation assets\n\n---\nAlternate route:\
        \ `/legacy/corporations/{corporation_id}/assets/`\n\n---\nThis route is cached\
        \ for up to 3600 seconds\n\n---\nRequires one of the following EVE corporation\
        \ role(s): Director\n\n\n---\nWarning: This route is deprecated.\n\n---\n\
        [Diff of the upcoming changes](https://esi.evetech.net/diff/v2/dev/#GET-/corporations/{corporation_id}/assets/)"
      operationId: "get_corporations_corporation_id_assets"
      security:
      - evesso:
        - "esi-assets.read_corporation_assets.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /corporations/{corporation_id}/assets/locations/:
    post:
      tags:
      - "Assets"
      summary: "Get corporation asset locations"
      description: "Return locations for a set of item ids, which you can get from\
        \ corporation assets endpoint. Coordinates for items in hangars or stations\
        \ are set to (0,0,0)\n\n---\nAlternate route: `/dev/corporations/{corporation_id}/assets/locations/`\n\
        \nAlternate route: `/latest/corporations/{corporation_id}/assets/locations/`\n\
        \n\n---\nRequires one of the following EVE corporation role(s): Director\n"
      operationId: "post_corporations_corporation_id_assets_locations"
      security:
      - evesso:
        - "esi-assets.read_corporation_assets.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-required-roles:
      - "Director"
  /corporations/{corporation_id}/blueprints/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation blueprints"
      description: "Returns a list of blueprints the corporation owns\n\n---\nAlternate\
        \ route: `/dev/corporations/{corporation_id}/blueprints/`\n\nAlternate route:\
        \ `/latest/corporations/{corporation_id}/blueprints/`\n\n---\nThis route is\
        \ cached for up to 3600 seconds\n\n---\nRequires one of the following EVE\
        \ corporation role(s): Director\n"
      operationId: "get_corporations_corporation_id_blueprints"
      security:
      - evesso:
        - "esi-corporations.read_blueprints.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /corporations/{corporation_id}/contacts/:
    get:
      tags:
      - "Contacts"
      summary: "Get corporation contacts"
      description: "Return contacts of a corporation\n\n---\nAlternate route: `/dev/corporations/{corporation_id}/contacts/`\n\
        \nAlternate route: `/latest/corporations/{corporation_id}/contacts/`\n\n---\n\
        This route is cached for up to 300 seconds"
      operationId: "get_corporations_corporation_id_contacts"
      security:
      - evesso:
        - "esi-corporations.read_contacts.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 300
      x-required-roles: []
  /corporations/{corporation_id}/containers/logs/:
    get:
      tags:
      - "Corporation"
      summary: "Get all corporation ALSC logs"
      description: "Returns logs recorded in the past seven days from all audit log\
        \ secure containers (ALSC) owned by a given corporation\n\n---\nAlternate\
        \ route: `/dev/corporations/{corporation_id}/containers/logs/`\n\nAlternate\
        \ route: `/latest/corporations/{corporation_id}/containers/logs/`\n\n---\n\
        This route is cached for up to 600 seconds\n\n---\nRequires one of the following\
        \ EVE corporation role(s): Director\n"
      operationId: "get_corporations_corporation_id_containers_logs"
      security:
      - evesso:
        - "esi-corporations.read_container_logs.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 600
      x-required-roles:
      - "Director"
  /corporations/{corporation_id}/members/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation members"
      description: "Read the current list of members if the calling character is a\
        \ member.\n\n---\nAlternate route: `/legacy/corporations/{corporation_id}/members/`\n\
        \n---\nThis route is cached for up to 3600 seconds\n\n---\nWarning: This route\
        \ is deprecated.\n\n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/v2/dev/#GET-/corporations/{corporation_id}/members/)"
      operationId: "get_corporations_corporation_id_members"
      security:
      - evesso:
        - "esi-corporations.read_corporation_membership.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
      x-cached-seconds: 3600
  /corporations/{corporation_id}/orders/:
    get:
      tags:
      - "Market"
      summary: "List open orders from a corporation"
      description: "List open market orders placed on behalf of a corporation\n\n\
        ---\nAlternate route: `/latest/corporations/{corporation_id}/orders/`\n\n\
        ---\nThis route is cached for up to 1200 seconds\n\n---\nRequires one of the\
        \ following EVE corporation role(s): Accountant, Trader\n\n\n---\nWarning:\
        \ This route has an upgrade available.\n\n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/v2/dev/#GET-/corporations/{corporation_id}/orders/)"
      operationId: "get_corporations_corporation_id_orders"
      security:
      - evesso:
        - "esi-markets.read_corporation_orders.v1"
      x-alternate-versions:
      - "latest"
      x-cached-seconds: 1200
      x-required-roles:
      - "Accountant"
      - "Trader"
  /corporations/{corporation_id}/orders/history/:
    get:
      tags:
      - "Market"
      summary: "List historical orders from a corporation"
      description: "List cancelled and expired market orders placed on behalf of a\
        \ corporation up to 90 days in the past.\n\n---\nAlternate route: `/dev/corporations/{corporation_id}/orders/history/`\n\
        \n---\nThis route is cached for up to 3600 seconds\n\n---\nRequires one of\
        \ the following EVE corporation role(s): Accountant, Trader\n"
      operationId: "get_corporations_corporation_id_orders_history"
      security:
      - evesso:
        - "esi-markets.read_corporation_orders.v1"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 3600
      x-required-roles:
      - "Accountant"
      - "Trader"
  /corporations/{corporation_id}/structures/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation structures"
      description: "Get a list of corporation structures. This route's version includes\
        \ the changes to structures detailed in this blog: https://www.eveonline.com/article/upwell-2.0-structures-changes-coming-on-february-13th\n\
        \n---\nAlternate route: `/dev/corporations/{corporation_id}/structures/`\n\
        \nAlternate route: `/latest/corporations/{corporation_id}/structures/`\n\n\
        ---\nThis route is cached for up to 3600 seconds\n\n---\nRequires one of the\
        \ following EVE corporation role(s): StationManager\n"
      operationId: "get_corporations_corporation_id_structures"
      security:
      - evesso:
        - "esi-corporations.read_structures.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
      x-required-roles:
      - "StationManager"
  /dogma/effects/{effect_id}/:
    get:
      tags:
      - "Dogma"
      summary: "Get effect information"
      description: "Get information on a dogma effect\n\n---\nAlternate route: `/dev/dogma/effects/{effect_id}/`\n\
        \nAlternate route: `/latest/dogma/effects/{effect_id}/`\n\n---\nThis route\
        \ expires daily at 11:05"
      operationId: "get_dogma_effects_effect_id"
      x-alternate-versions:
      - "dev"
      - "latest"
  /fw/systems/:
    get:
      tags:
      - "Faction Warfare"
      summary: "Ownership of faction warfare systems"
      description: "An overview of the current ownership of faction warfare solar\
        \ systems\n\n---\nAlternate route: `/dev/fw/systems/`\n\nAlternate route:\
        \ `/latest/fw/systems/`\n\n---\nThis route is cached for up to 1800 seconds"
      operationId: "get_fw_systems"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 1800
  /search/:
    get:
      tags:
      - "Search"
      summary: "Search on a string"
      description: "Search for entities that match a given sub-string.\n\n---\nAlternate\
        \ route: `/dev/search/`\n\nAlternate route: `/latest/search/`\n\n---\nThis\
        \ route is cached for up to 3600 seconds"
      operationId: "get_search"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
  /ui/autopilot/waypoint/:
    post:
      tags:
      - "User Interface"
      summary: "Set Autopilot Waypoint"
      description: "Set a solar system as autopilot waypoint\n\n---\nAlternate route:\
        \ `/dev/ui/autopilot/waypoint/`\n\nAlternate route: `/latest/ui/autopilot/waypoint/`\n"
      operationId: "post_ui_autopilot_waypoint"
      security:
      - evesso:
        - "esi-ui.write_waypoint.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
  /universe/factions/:
    get:
      tags:
      - "Universe"
      summary: "Get factions"
      description: "Get a list of factions\n\n---\nAlternate route: `/dev/universe/factions/`\n\
        \nAlternate route: `/latest/universe/factions/`\n\n---\nThis route expires\
        \ daily at 11:05"
      operationId: "get_universe_factions"
      x-alternate-versions:
      - "dev"
      - "latest"
  /universe/names/:
    post:
      tags:
      - "Universe"
      summary: "Get names and categories for a set of ID's"
      description: "Resolve a set of IDs to names and categories. Supported ID's for\
        \ resolving are: Characters, Corporations, Alliances, Stations, Solar Systems,\
        \ Constellations, Regions, Types.\n\n---\nAlternate route: `/dev/universe/names/`\n\
        \nAlternate route: `/latest/universe/names/`\n"
      operationId: "post_universe_names"
      x-alternate-versions:
      - "dev"
      - "latest"
  /universe/stations/{station_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get station information"
      description: "Get information on a station\n\n---\nAlternate route: `/dev/universe/stations/{station_id}/`\n\
        \nAlternate route: `/latest/universe/stations/{station_id}/`\n\n---\nThis\
        \ route expires daily at 11:05"
      operationId: "get_universe_stations_station_id"
      x-alternate-versions:
      - "dev"
      - "latest"
  /universe/structures/{structure_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get structure information"
      description: "Returns information on requested structure if you are on the ACL.\
        \ Otherwise, returns \"Forbidden\" for all inputs.\n\n---\nAlternate route:\
        \ `/dev/universe/structures/{structure_id}/`\n\n---\nThis route is cached\
        \ for up to 3600 seconds"
      operationId: "get_universe_structures_structure_id"
      security:
      - evesso:
        - "esi-universe.read_structures.v1"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 3600
  /universe/system_kills/:
    get:
      tags:
      - "Universe"
      summary: "Get system kills"
      description: "Get the number of ship, pod and NPC kills per solar system within\
        \ the last hour ending at the timestamp of the Last-Modified header, excluding\
        \ wormhole space. Only systems with kills will be listed\n\n---\nAlternate\
        \ route: `/dev/universe/system_kills/`\n\nAlternate route: `/latest/universe/system_kills/`\n\
        \n---\nThis route is cached for up to 3600 seconds"
      operationId: "get_universe_system_kills"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
  /universe/systems/{system_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get solar system information"
      description: "Get information on a solar system\n\n---\nAlternate route: `/legacy/universe/systems/{system_id}/`\n\
        \n---\nThis route expires daily at 11:05\n\n---\nWarning: This route is deprecated.\n\
        \n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/v2/dev/#GET-/universe/systems/{system_id}/)"
      operationId: "get_universe_systems_system_id"
      deprecated: true
      x-alternate-versions:
      - "legacy"
  /universe/types/{type_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get type information"
      description: "Get information on a type\n\n---\nAlternate route: `/legacy/universe/types/{type_id}/`\n\
        \n---\nThis route expires daily at 11:05\n\n---\nWarning: This route is deprecated.\n\
        \n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/v2/dev/#GET-/universe/types/{type_id}/)"
      operationId: "get_universe_types_type_id"
      deprecated: true
      x-alternate-versions:
      - "legacy"
securityDefinitions:
  evesso:
    type: "oauth2"
    authorizationUrl: "https://login.eveonline.com/oauth/authorize"
    flow: "implicit"
    scopes:
      esi-alliances.read_contacts.v1: "EVE SSO scope esi-alliances.read_contacts.v1"
      esi-assets.read_assets.v1: "EVE SSO scope esi-assets.read_assets.v1"
      esi-assets.read_corporation_assets.v1: "EVE SSO scope esi-assets.read_corporation_assets.v1"
      esi-bookmarks.read_character_bookmarks.v1: "EVE SSO scope esi-bookmarks.read_character_bookmarks.v1"
      esi-calendar.read_calendar_events.v1: "EVE SSO scope esi-calendar.read_calendar_events.v1"
      esi-calendar.respond_calendar_events.v1: "EVE SSO scope esi-calendar.respond_calendar_events.v1"
      esi-characters.read_blueprints.v1: "EVE SSO scope esi-characters.read_blueprints.v1"
      esi-characters.read_contacts.v1: "EVE SSO scope esi-characters.read_contacts.v1"
      esi-characters.read_corporation_roles.v1: "EVE SSO scope esi-characters.read_corporation_roles.v1"
      esi-characters.read_notifications.v1: "EVE SSO scope esi-characters.read_notifications.v1"
      esi-characters.write_contacts.v1: "EVE SSO scope esi-characters.write_contacts.v1"
      esi-characterstats.read.v1: "EVE SSO scope esi-characterstats.read.v1"
      esi-clones.read_clones.v1: "EVE SSO scope esi-clones.read_clones.v1"
      esi-corporations.read_blueprints.v1: "EVE SSO scope esi-corporations.read_blueprints.v1"
      esi-corporations.read_contacts.v1: "EVE SSO scope esi-corporations.read_contacts.v1"
      esi-corporations.read_container_logs.v1: "EVE SSO scope esi-corporations.read_container_logs.v1"
      esi-corporations.read_corporation_membership.v1: "EVE SSO scope esi-corporations.read_corporation_membership.v1"
      esi-corporations.read_structures.v1: "EVE SSO scope esi-corporations.read_structures.v1"
      esi-location.read_online.v1: "EVE SSO scope esi-location.read_online.v1"
      esi-mail.organize_mail.v1: "EVE SSO scope esi-mail.organize_mail.v1"
      esi-mail.read_mail.v1: "EVE SSO scope esi-mail.read_mail.v1"
      esi-markets.read_character_orders.v1: "EVE SSO scope esi-markets.read_character_orders.v1"
      esi-markets.read_corporation_orders.v1: "EVE SSO scope esi-markets.read_corporation_orders.v1"
      esi-planets.manage_planets.v1: "EVE SSO scope esi-planets.manage_planets.v1"
      esi-search.search_structures.v1: "EVE SSO scope esi-search.search_structures.v1"
      esi-skills.read_skillqueue.v1: "EVE SSO scope esi-skills.read_skillqueue.v1"
      esi-ui.write_waypoint.v1: "EVE SSO scope esi-ui.write_waypoint.v1"
      esi-universe.read_structures.v1: "EVE SSO scope esi-universe.read_structures.v1"