language: go
go: 1.8.1

services:
  - docker

install:
  - go get -u github.com/antihax/mock-esi
  - CGO_ENABLED=0 GOOS=linux go build -a --installsuffix cgo -o mock-esi .
  - docker build -t antihax/mock-esi .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push antihax/mock-esi;
    fi