sudo: required
language: go
go: master

services:
  - docker

install:
  - docker build -t antihax/mock-esi .
  - docker run -d -p 80:8080 --name mock-esi antihax/mock-esi

script:
  - go get github.com/gorilla/mux
  - go test 

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push antihax/mock-esi;
    fi