---
swagger: "2.0"
info:
  description: "An OpenAPI for EVE Online"
  version: "1.24"
  title: "EVE Swagger Interface"
host: "esi.evetech.net"
basePath: "/v3"
schemes:
- "https"
paths:
  /alliances/{alliance_id}/:
    get:
      tags:
      - "Alliance"
      summary: "Get alliance information"
      description: "Public information about an alliance\n\n---\nAlternate route:\
        \ `/dev/alliances/{alliance_id}/`\n\nAlternate route: `/latest/alliances/{alliance_id}/`\n\
        \nAlternate route: `/legacy/alliances/{alliance_id}/`\n\nAlternate route:\
        \ `/v4/alliances/{alliance_id}/`\n\n---\nThis route is cached for up to 3600\
        \ seconds"
      operationId: "get_alliances_alliance_id"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v4"
      x-cached-seconds: 3600
  /characters/{character_id}/blueprints/:
    get:
      tags:
      - "Character"
      summary: "Get blueprints"
      description: "Return a list of blueprints the character owns\n\n---\nAlternate\
        \ route: `/dev/characters/{character_id}/blueprints/`\n\nAlternate route:\
        \ `/latest/characters/{character_id}/blueprints/`\n\n---\nThis route is cached\
        \ for up to 3600 seconds"
      operationId: "get_characters_character_id_blueprints"
      security:
      - evesso:
        - "esi-characters.read_blueprints.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
  /characters/{character_id}/calendar/{event_id}/:
    get:
      tags:
      - "Calendar"
      summary: "Get an event"
      description: "Get all the information for a specific event\n\n---\nAlternate\
        \ route: `/dev/characters/{character_id}/calendar/{event_id}/`\n\nAlternate\
        \ route: `/latest/characters/{character_id}/calendar/{event_id}/`\n\nAlternate\
        \ route: `/legacy/characters/{character_id}/calendar/{event_id}/`\n\nAlternate\
        \ route: `/v4/characters/{character_id}/calendar/{event_id}/`\n\n---\nThis\
        \ route is cached for up to 5 seconds"
      operationId: "get_characters_character_id_calendar_event_id"
      security:
      - evesso:
        - "esi-calendar.read_calendar_events.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v4"
      x-cached-seconds: 5
    put:
      tags:
      - "Calendar"
      summary: "Respond to an event"
      description: "Set your response status to an event\n\n---\nAlternate route:\
        \ `/dev/characters/{character_id}/calendar/{event_id}/`\n\nAlternate route:\
        \ `/latest/characters/{character_id}/calendar/{event_id}/`\n\nAlternate route:\
        \ `/legacy/characters/{character_id}/calendar/{event_id}/`\n\nAlternate route:\
        \ `/v4/characters/{character_id}/calendar/{event_id}/`\n\n---\nThis route\
        \ is cached for up to 5 seconds"
      operationId: "put_characters_character_id_calendar_event_id"
      security:
      - evesso:
        - "esi-calendar.respond_calendar_events.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v4"
      x-cached-seconds: 5
  /characters/{character_id}/clones/:
    get:
      tags:
      - "Clones"
      summary: "Get clones"
      description: "A list of the character's clones\n\n---\nAlternate route: `/dev/characters/{character_id}/clones/`\n\
        \nAlternate route: `/latest/characters/{character_id}/clones/`\n\nAlternate\
        \ route: `/v4/characters/{character_id}/clones/`\n\n---\nThis route is cached\
        \ for up to 120 seconds"
      operationId: "get_characters_character_id_clones"
      security:
      - evesso:
        - "esi-clones.read_clones.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "v4"
      x-cached-seconds: 120
  /characters/{character_id}/mail/labels/:
    get:
      tags:
      - "Mail"
      summary: "Get mail labels and unread counts"
      description: "Return a list of the users mail labels, unread counts for each\
        \ label and a total unread count.\n\n---\nAlternate route: `/dev/characters/{character_id}/mail/labels/`\n\
        \nAlternate route: `/latest/characters/{character_id}/mail/labels/`\n\n---\n\
        This route is cached for up to 30 seconds"
      operationId: "get_characters_character_id_mail_labels"
      security:
      - evesso:
        - "esi-mail.read_mail.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 30
  /characters/{character_id}/online/:
    get:
      tags:
      - "Location"
      summary: "Get character online"
      description: "Checks if the character is currently online\n\n---\nAlternate\
        \ route: `/dev/characters/{character_id}/online/`\n\nAlternate route: `/latest/characters/{character_id}/online/`\n\
        \nAlternate route: `/v2/characters/{character_id}/online/`\n\n---\nThis route\
        \ is cached for up to 60 seconds"
      operationId: "get_characters_character_id_online"
      security:
      - evesso:
        - "esi-location.read_online.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "v2"
      x-cached-seconds: 60
  /characters/{character_id}/planets/{planet_id}/:
    get:
      tags:
      - "Planetary Interaction"
      summary: "Get colony layout"
      description: "Returns full details on the layout of a single planetary colony,\
        \ including links, pins and routes. Note: Planetary information is only recalculated\
        \ when the colony is viewed through the client. Information will not update\
        \ until this criteria is met.\n\n---\nAlternate route: `/dev/characters/{character_id}/planets/{planet_id}/`\n\
        \nAlternate route: `/latest/characters/{character_id}/planets/{planet_id}/`\n"
      operationId: "get_characters_character_id_planets_planet_id"
      security:
      - evesso:
        - "esi-planets.manage_planets.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
  /characters/{character_id}/portrait/:
    get:
      tags:
      - "Character"
      summary: "Get character portraits"
      description: "Get portrait urls for a character\n\n---\nAlternate route: `/dev/characters/{character_id}/portrait/`\n\
        \nAlternate route: `/latest/characters/{character_id}/portrait/`\n\nAlternate\
        \ route: `/v2/characters/{character_id}/portrait/`\n\n---\nThis route expires\
        \ daily at 11:05"
      operationId: "get_characters_character_id_portrait"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "v2"
  /characters/{character_id}/roles/:
    get:
      tags:
      - "Character"
      summary: "Get character corporation roles"
      description: "Returns a character's corporation roles\n\n---\nAlternate route:\
        \ `/dev/characters/{character_id}/roles/`\n\nAlternate route: `/latest/characters/{character_id}/roles/`\n\
        \n---\nThis route is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_roles"
      security:
      - evesso:
        - "esi-characters.read_corporation_roles.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
  /characters/{character_id}/search/:
    get:
      tags:
      - "Search"
      summary: "Search on a string"
      description: "Search for entities that match a given sub-string.\n\n---\nAlternate\
        \ route: `/dev/characters/{character_id}/search/`\n\nAlternate route: `/latest/characters/{character_id}/search/`\n\
        \nAlternate route: `/legacy/characters/{character_id}/search/`\n\n---\nThis\
        \ route is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_search"
      security:
      - evesso:
        - "esi-search.search_structures.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      x-cached-seconds: 3600
  /characters/{character_id}/skills/:
    get:
      tags:
      - "Skills"
      summary: "Get character skills"
      description: "List all trained skills for the given character\n\n---\nAlternate\
        \ route: `/legacy/characters/{character_id}/skills/`\n\n---\nThis route is\
        \ cached for up to 120 seconds\n\n---\nWarning: This route is deprecated\n\
        \n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/v3/dev/#GET-/characters/{character_id}/skills/)"
      operationId: "get_characters_character_id_skills"
      security:
      - evesso:
        - "esi-skills.read_skills.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
      x-cached-seconds: 120
  /corporations/{corporation_id}/alliancehistory/:
    get:
      tags:
      - "Corporation"
      summary: "Get alliance history"
      description: "Get a list of all the alliances a corporation has been a member\
        \ of\n\n---\nAlternate route: `/dev/corporations/{corporation_id}/alliancehistory/`\n\
        \nAlternate route: `/latest/corporations/{corporation_id}/alliancehistory/`\n\
        \n---\nThis route is cached for up to 3600 seconds"
      operationId: "get_corporations_corporation_id_alliancehistory"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
  /corporations/{corporation_id}/blueprints/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation blueprints"
      description: "Returns a list of blueprints the corporation owns\n\n---\nAlternate\
        \ route: `/dev/corporations/{corporation_id}/blueprints/`\n\nAlternate route:\
        \ `/latest/corporations/{corporation_id}/blueprints/`\n\n---\nThis route is\
        \ cached for up to 3600 seconds\n\n---\nRequires one of the following EVE\
        \ corporation role(s): Director\n"
      operationId: "get_corporations_corporation_id_blueprints"
      security:
      - evesso:
        - "esi-corporations.read_blueprints.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /corporations/{corporation_id}/containers/logs/:
    get:
      tags:
      - "Corporation"
      summary: "Get all corporation ALSC logs"
      description: "Returns logs recorded in the past seven days from all audit log\
        \ secure containers (ALSC) owned by a given corporation\n\n---\nAlternate\
        \ route: `/dev/corporations/{corporation_id}/containers/logs/`\n\nAlternate\
        \ route: `/latest/corporations/{corporation_id}/containers/logs/`\n\n---\n\
        This route is cached for up to 600 seconds\n\n---\nRequires one of the following\
        \ EVE corporation role(s): Director\n"
      operationId: "get_corporations_corporation_id_containers_logs"
      security:
      - evesso:
        - "esi-corporations.read_container_logs.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 600
      x-required-roles:
      - "Director"
  /corporations/{corporation_id}/members/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation members"
      description: "Return the current member list of a corporation, the token's character\
        \ need to be a member of the corporation.\n\n---\nAlternate route: `/legacy/corporations/{corporation_id}/members/`\n\
        \n---\nThis route is cached for up to 3600 seconds\n\n---\nWarning: This route\
        \ is deprecated\n\n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/v3/dev/#GET-/corporations/{corporation_id}/members/)"
      operationId: "get_corporations_corporation_id_members"
      security:
      - evesso:
        - "esi-corporations.read_corporation_membership.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
      x-cached-seconds: 3600
  /corporations/{corporation_id}/orders/:
    get:
      tags:
      - "Market"
      summary: "List open orders from a corporation"
      description: "List open market orders placed on behalf of a corporation\n\n\
        ---\nAlternate route: `/dev/corporations/{corporation_id}/orders/`\n\nAlternate\
        \ route: `/latest/corporations/{corporation_id}/orders/`\n\n---\nThis route\
        \ is cached for up to 1200 seconds\n\n---\nRequires one of the following EVE\
        \ corporation role(s): Accountant, Trader\n"
      operationId: "get_corporations_corporation_id_orders"
      security:
      - evesso:
        - "esi-markets.read_corporation_orders.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 1200
      x-required-roles:
      - "Accountant"
      - "Trader"
  /corporations/{corporation_id}/structures/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation structures"
      description: "Get a list of corporation structures. This route's version includes\
        \ the changes to structures detailed in this blog: https://www.eveonline.com/article/upwell-2.0-structures-changes-coming-on-february-13th\n\
        \n---\nAlternate route: `/legacy/corporations/{corporation_id}/structures/`\n\
        \n---\nThis route is cached for up to 3600 seconds\n\n---\nRequires one of\
        \ the following EVE corporation role(s): Station_Manager\n\n\n---\nWarning:\
        \ This route is deprecated\n\n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/v3/dev/#GET-/corporations/{corporation_id}/structures/)"
      operationId: "get_corporations_corporation_id_structures"
      security:
      - evesso:
        - "esi-corporations.read_structures.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
      x-cached-seconds: 3600
      x-required-roles:
      - "Station_Manager"
  /corporations/{corporation_id}/wallets/{division}/journal/:
    get:
      tags:
      - "Wallet"
      summary: "Get corporation wallet journal"
      description: "Retrieve the given corporation's wallet journal for the given\
        \ division going 30 days back. Note: any journal records having to do with\
        \ the new navigation structures from the release of Onslaught will not show\
        \ up in this version. To see those, use the v4 version of this route.\n\n\
        ---\nAlternate route: `/legacy/corporations/{corporation_id}/wallets/{division}/journal/`\n\
        \n---\nThis route is cached for up to 3600 seconds\n\n---\nRequires one of\
        \ the following EVE corporation role(s): Accountant, Junior_Accountant\n\n\
        \n---\nWarning: This route is deprecated\n\n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/v3/dev/#GET-/corporations/{corporation_id}/wallets/{division}/journal/)"
      operationId: "get_corporations_corporation_id_wallets_division_journal"
      security:
      - evesso:
        - "esi-wallet.read_corporation_wallets.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
      x-cached-seconds: 3600
      x-required-roles:
      - "Accountant"
      - "Junior_Accountant"
  /fw/systems/:
    get:
      tags:
      - "Faction Warfare"
      summary: "Ownership of faction warfare systems"
      description: "An overview of the current ownership of faction warfare solar\
        \ systems\n\n---\nAlternate route: `/dev/fw/systems/`\n\nAlternate route:\
        \ `/latest/fw/systems/`\n\nAlternate route: `/legacy/fw/systems/`\n\nAlternate\
        \ route: `/v2/fw/systems/`\n\n---\nThis route is cached for up to 1800 seconds"
      operationId: "get_fw_systems"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v2"
      x-cached-seconds: 1800
  /universe/names/:
    post:
      tags:
      - "Universe"
      summary: "Get names and categories for a set of IDs"
      description: "Resolve a set of IDs to names and categories. Supported ID's for\
        \ resolving are: Characters, Corporations, Alliances, Stations, Solar Systems,\
        \ Constellations, Regions, Types, Factions\n\n---\nAlternate route: `/dev/universe/names/`\n\
        \nAlternate route: `/latest/universe/names/`\n"
      operationId: "post_universe_names"
      x-alternate-versions:
      - "dev"
      - "latest"
  /universe/structures/{structure_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get structure information"
      description: "Returns information on requested structure if you are on the ACL.\
        \ Otherwise, returns \"Forbidden\" for all inputs.\n\n---\nAlternate route:\
        \ `/dev/universe/structures/{structure_id}/`\n\n---\nThis route is cached\
        \ for up to 3600 seconds"
      operationId: "get_universe_structures_structure_id"
      security:
      - evesso:
        - "esi-universe.read_structures.v1"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 3600
  /universe/system_kills/:
    get:
      tags:
      - "Universe"
      summary: "Get system kills"
      description: "Get the number of ship, pod and NPC kills per solar system within\
        \ the last hour ending at the timestamp of the Last-Modified header, excluding\
        \ wormhole space. Only systems with kills will be listed\n\n---\nAlternate\
        \ route: `/dev/universe/system_kills/`\n\n---\nThis route is cached for up\
        \ to 3600 seconds"
      operationId: "get_universe_system_kills"
      x-alternate-versions:
      - "dev"
      x-cached-seconds: 3600
  /universe/systems/{system_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get solar system information"
      description: "Get information on a solar system. NOTE: This route does not work\
        \ with abyssal systems.\n\n---\nAlternate route: `/legacy/universe/systems/{system_id}/`\n\
        \n---\nThis route expires daily at 11:05\n\n---\nWarning: This route is deprecated\n\
        \n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/v3/dev/#GET-/universe/systems/{system_id}/)"
      operationId: "get_universe_systems_system_id"
      deprecated: true
      x-alternate-versions:
      - "legacy"
  /universe/types/{type_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get type information"
      description: "Get information on a type\n\n---\nAlternate route: `/dev/universe/types/{type_id}/`\n\
        \nAlternate route: `/latest/universe/types/{type_id}/`\n\n---\nThis route\
        \ expires daily at 11:05"
      operationId: "get_universe_types_type_id"
      x-alternate-versions:
      - "dev"
      - "latest"
securityDefinitions:
  evesso:
    type: "oauth2"
    authorizationUrl: "https://login.eveonline.com/v2/oauth/authorize"
    flow: "implicit"
    scopes:
      esi-calendar.read_calendar_events.v1: "EVE SSO scope esi-calendar.read_calendar_events.v1"
      esi-calendar.respond_calendar_events.v1: "EVE SSO scope esi-calendar.respond_calendar_events.v1"
      esi-characters.read_blueprints.v1: "EVE SSO scope esi-characters.read_blueprints.v1"
      esi-characters.read_corporation_roles.v1: "EVE SSO scope esi-characters.read_corporation_roles.v1"
      esi-clones.read_clones.v1: "EVE SSO scope esi-clones.read_clones.v1"
      esi-corporations.read_blueprints.v1: "EVE SSO scope esi-corporations.read_blueprints.v1"
      esi-corporations.read_container_logs.v1: "EVE SSO scope esi-corporations.read_container_logs.v1"
      esi-corporations.read_corporation_membership.v1: "EVE SSO scope esi-corporations.read_corporation_membership.v1"
      esi-corporations.read_structures.v1: "EVE SSO scope esi-corporations.read_structures.v1"
      esi-location.read_online.v1: "EVE SSO scope esi-location.read_online.v1"
      esi-mail.read_mail.v1: "EVE SSO scope esi-mail.read_mail.v1"
      esi-markets.read_corporation_orders.v1: "EVE SSO scope esi-markets.read_corporation_orders.v1"
      esi-planets.manage_planets.v1: "EVE SSO scope esi-planets.manage_planets.v1"
      esi-search.search_structures.v1: "EVE SSO scope esi-search.search_structures.v1"
      esi-skills.read_skills.v1: "EVE SSO scope esi-skills.read_skills.v1"
      esi-universe.read_structures.v1: "EVE SSO scope esi-universe.read_structures.v1"
      esi-wallet.read_corporation_wallets.v1: "EVE SSO scope esi-wallet.read_corporation_wallets.v1"