---
swagger: "2.0"
info:
  description: "An OpenAPI for EVE Online"
  version: "0.7.5"
  title: "EVE Swagger Interface"
host: "esi.tech.ccp.is"
basePath: "/v3"
schemes:
- "https"
paths:
  /alliances/{alliance_id}/:
    get:
      tags:
      - "Alliance"
      summary: "Get alliance information"
      description: "Public information about an alliance\n\n---\nAlternate route:\
        \ `/dev/alliances/{alliance_id}/`\n\nAlternate route: `/latest/alliances/{alliance_id}/`\n\
        \n---\nThis route is cached for up to 3600 seconds"
      operationId: "get_alliances_alliance_id"
      x-cached-seconds: 3600
      x-alternate-versions:
      - "dev"
      - "latest"
  /characters/{character_id}/assets/:
    get:
      tags:
      - "Assets"
      summary: "Get character assets"
      description: "Return a list of the characters assets\n\n---\nAlternate route:\
        \ `/dev/characters/{character_id}/assets/`\n\nAlternate route: `/latest/characters/{character_id}/assets/`\n\
        \n---\nThis route is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_assets"
      security:
      - evesso:
        - "esi-assets.read_assets.v1"
      x-cached-seconds: 3600
      x-alternate-versions:
      - "dev"
      - "latest"
  /corporations/{corporation_id}/assets/:
    get:
      tags:
      - "Assets"
      summary: "Get corporation assets"
      description: "Return a list of the corporation assets\n\n---\nAlternate route:\
        \ `/dev/corporations/{corporation_id}/assets/`\n\n---\nThis route is cached\
        \ for up to 3600 seconds\n\n---\nRequires one of the following EVE corporation\
        \ role(s): Director\n"
      operationId: "get_corporations_corporation_id_assets"
      security:
      - evesso:
        - "esi-assets.read_corporation_assets.v1"
      x-required-roles:
      - "Director"
      x-cached-seconds: 3600
      x-alternate-versions:
      - "dev"
  /characters/{character_id}/calendar/{event_id}/:
    get:
      tags:
      - "Calendar"
      summary: "Get an event"
      description: "Get all the information for a specific event\n\n---\nAlternate\
        \ route: `/dev/characters/{character_id}/calendar/{event_id}/`\n\nAlternate\
        \ route: `/latest/characters/{character_id}/calendar/{event_id}/`\n\n---\n\
        This route is cached for up to 5 seconds"
      operationId: "get_characters_character_id_calendar_event_id"
      security:
      - evesso:
        - "esi-calendar.read_calendar_events.v1"
      x-cached-seconds: 5
      x-alternate-versions:
      - "dev"
      - "latest"
    put:
      tags:
      - "Calendar"
      summary: "Respond to an event"
      description: "Set your response status to an event\n\n---\nAlternate route:\
        \ `/dev/characters/{character_id}/calendar/{event_id}/`\n\nAlternate route:\
        \ `/latest/characters/{character_id}/calendar/{event_id}/`\n"
      operationId: "put_characters_character_id_calendar_event_id"
      security:
      - evesso:
        - "esi-calendar.respond_calendar_events.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
  /characters/{character_id}/:
    get:
      tags:
      - "Character"
      summary: "Get character's public information"
      description: "Public information about a character\n\n---\nAlternate route:\
        \ `/legacy/characters/{character_id}/`\n\n---\nThis route is cached for up\
        \ to 3600 seconds\n\n---\nWarning: This route is deprecated.\n\n---\n[This\
        \ route has an available update](https://esi.tech.ccp.is/diff/v3/dev/#GET-/characters/{character_id}/)"
      operationId: "get_characters_character_id"
      deprecated: true
      x-cached-seconds: 3600
      x-alternate-versions:
      - "legacy"
  /characters/{character_id}/cspa/:
    post:
      tags:
      - "Character"
      summary: "Calculate a CSPA charge cost"
      description: "Takes a source character ID in the url and a set of target character\
        \ ID's in the body, returns a CSPA charge cost\n\n---\nAlternate route: `/legacy/characters/{character_id}/cspa/`\n\
        \n\n---\nWarning: This route is deprecated.\n\n---\n[This route has an available\
        \ update](https://esi.tech.ccp.is/diff/v3/dev/#POST-/characters/{character_id}/cspa/)"
      operationId: "post_characters_character_id_cspa"
      security:
      - evesso:
        - "esi-characters.read_contacts.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
  /characters/{character_id}/clones/:
    get:
      tags:
      - "Clones"
      summary: "Get clones"
      description: "A list of the character's clones\n\n---\nAlternate route: `/dev/characters/{character_id}/clones/`\n\
        \nAlternate route: `/latest/characters/{character_id}/clones/`\n\n---\nThis\
        \ route is cached for up to 120 seconds"
      operationId: "get_characters_character_id_clones"
      security:
      - evesso:
        - "esi-clones.read_clones.v1"
      x-cached-seconds: 120
      x-alternate-versions:
      - "dev"
      - "latest"
  /corporations/{corporation_id}/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation information"
      description: "Public information about a corporation\n\n---\nAlternate route:\
        \ `/legacy/corporations/{corporation_id}/`\n\n---\nThis route is cached for\
        \ up to 3600 seconds\n\n---\nWarning: This route is deprecated.\n\n---\n[This\
        \ route has an available update](https://esi.tech.ccp.is/diff/v3/dev/#GET-/corporations/{corporation_id}/)"
      operationId: "get_corporations_corporation_id"
      deprecated: true
      x-cached-seconds: 3600
      x-alternate-versions:
      - "legacy"
  /corporations/{corporation_id}/members/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation members"
      description: "Return the current member list of a corporation, the token's character\
        \ need to be a member of the corporation.\n\n---\nAlternate route: `/dev/corporations/{corporation_id}/members/`\n\
        \nAlternate route: `/latest/corporations/{corporation_id}/members/`\n\n---\n\
        This route is cached for up to 3600 seconds"
      operationId: "get_corporations_corporation_id_members"
      security:
      - evesso:
        - "esi-corporations.read_corporation_membership.v1"
      x-cached-seconds: 3600
      x-alternate-versions:
      - "dev"
      - "latest"
  /characters/{character_id}/mail/labels/:
    get:
      tags:
      - "Mail"
      summary: "Get mail labels and unread counts"
      description: "Return a list of the users mail labels, unread counts for each\
        \ label and a total unread count.\n\n---\nAlternate route: `/dev/characters/{character_id}/mail/labels/`\n\
        \nAlternate route: `/latest/characters/{character_id}/mail/labels/`\n\n---\n\
        This route is cached for up to 30 seconds"
      operationId: "get_characters_character_id_mail_labels"
      security:
      - evesso:
        - "esi-mail.read_mail.v1"
      x-cached-seconds: 30
      x-alternate-versions:
      - "dev"
      - "latest"
  /characters/{character_id}/planets/{planet_id}/:
    get:
      tags:
      - "Planetary Interaction"
      summary: "Get colony layout"
      description: "Returns full details on the layout of a single planetary colony,\
        \ including links, pins and routes. Note: Planetary information is only recalculated\
        \ when the colony is viewed through the client. Information will not update\
        \ until this criteria is met.\n\n---\nAlternate route: `/dev/characters/{character_id}/planets/{planet_id}/`\n\
        \nAlternate route: `/latest/characters/{character_id}/planets/{planet_id}/`\n\
        \n---\nThis route is cached for up to 600 seconds"
      operationId: "get_characters_character_id_planets_planet_id"
      security:
      - evesso:
        - "esi-planets.manage_planets.v1"
      x-cached-seconds: 600
      x-alternate-versions:
      - "dev"
      - "latest"
  /characters/{character_id}/search/:
    get:
      tags:
      - "Search"
      summary: "Search on a string"
      description: "Search for entities that match a given sub-string.\n\n---\nAlternate\
        \ route: `/dev/characters/{character_id}/search/`\n\nAlternate route: `/latest/characters/{character_id}/search/`\n\
        \n---\nThis route is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_search"
      security:
      - evesso:
        - "esi-search.search_structures.v1"
      x-cached-seconds: 3600
      x-alternate-versions:
      - "dev"
      - "latest"
  /characters/{character_id}/skills/:
    get:
      tags:
      - "Skills"
      summary: "Get character skills"
      description: "List all trained skills for the given character\n\n---\nAlternate\
        \ route: `/legacy/characters/{character_id}/skills/`\n\n---\nThis route is\
        \ cached for up to 120 seconds\n\n---\nWarning: This route is deprecated.\n\
        \n---\n[This route has an available update](https://esi.tech.ccp.is/diff/v3/dev/#GET-/characters/{character_id}/skills/)"
      operationId: "get_characters_character_id_skills"
      security:
      - evesso:
        - "esi-skills.read_skills.v1"
      deprecated: true
      x-cached-seconds: 120
      x-alternate-versions:
      - "legacy"
  /universe/systems/{system_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get solar system information"
      description: "Get information on a solar system\n\n---\nAlternate route: `/dev/universe/systems/{system_id}/`\n\
        \nAlternate route: `/latest/universe/systems/{system_id}/`\n\n---\nThis route\
        \ expires daily at 11:05"
      operationId: "get_universe_systems_system_id"
      x-alternate-versions:
      - "dev"
      - "latest"
  /universe/types/{type_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get type information"
      description: "Get information on a type\n\n---\nAlternate route: `/dev/universe/types/{type_id}/`\n\
        \nAlternate route: `/latest/universe/types/{type_id}/`\n\n---\nThis route\
        \ expires daily at 11:05"
      operationId: "get_universe_types_type_id"
      x-alternate-versions:
      - "dev"
      - "latest"
  /characters/{character_id}/wallet/journal/:
    get:
      tags:
      - "Wallet"
      summary: "Get character wallet journal"
      description: "Retrieve character wallet journal\n\n---\nAlternate route: `/latest/characters/{character_id}/wallet/journal/`\n\
        \n---\nThis route is cached for up to 3600 seconds\n\n---\n[This route has\
        \ an available update](https://esi.tech.ccp.is/diff/v3/dev/#GET-/characters/{character_id}/wallet/journal/)"
      operationId: "get_characters_character_id_wallet_journal"
      security:
      - evesso:
        - "esi-wallet.read_character_wallet.v1"
      x-cached-seconds: 3600
      x-alternate-versions:
      - "latest"
  /corporations/{corporation_id}/wallets/{division}/journal/:
    get:
      tags:
      - "Wallet"
      summary: "Get corporation wallet journal"
      description: "Retrieve the given corporation's wallet journal for the given\
        \ division going 30 days back\n\n---\nAlternate route: `/dev/corporations/{corporation_id}/wallets/{division}/journal/`\n\
        \n---\nThis route is cached for up to 3600 seconds\n\n---\nRequires one of\
        \ the following EVE corporation role(s): Accountant, Junior_Accountant\n"
      operationId: "get_corporations_corporation_id_wallets_division_journal"
      security:
      - evesso:
        - "esi-wallet.read_corporation_wallets.v1"
      x-required-roles:
      - "Accountant"
      - "Junior_Accountant"
      x-cached-seconds: 3600
      x-alternate-versions:
      - "dev"
securityDefinitions:
  evesso:
    type: "oauth2"
    authorizationUrl: "https://login.eveonline.com/oauth/authorize"
    flow: "implicit"
    scopes:
      esi-assets.read_assets.v1: "EVE SSO scope esi-assets.read_assets.v1"
      esi-assets.read_corporation_assets.v1: "EVE SSO scope esi-assets.read_corporation_assets.v1"
      esi-calendar.read_calendar_events.v1: "EVE SSO scope esi-calendar.read_calendar_events.v1"
      esi-calendar.respond_calendar_events.v1: "EVE SSO scope esi-calendar.respond_calendar_events.v1"
      esi-characters.read_contacts.v1: "EVE SSO scope esi-characters.read_contacts.v1"
      esi-clones.read_clones.v1: "EVE SSO scope esi-clones.read_clones.v1"
      esi-corporations.read_corporation_membership.v1: "EVE SSO scope esi-corporations.read_corporation_membership.v1"
      esi-mail.read_mail.v1: "EVE SSO scope esi-mail.read_mail.v1"
      esi-planets.manage_planets.v1: "EVE SSO scope esi-planets.manage_planets.v1"
      esi-search.search_structures.v1: "EVE SSO scope esi-search.search_structures.v1"
      esi-skills.read_skills.v1: "EVE SSO scope esi-skills.read_skills.v1"
      esi-wallet.read_character_wallet.v1: "EVE SSO scope esi-wallet.read_character_wallet.v1"
      esi-wallet.read_corporation_wallets.v1: "EVE SSO scope esi-wallet.read_corporation_wallets.v1"