---
swagger: "2.0"
info:
  description: "An OpenAPI for EVE Online"
  version: "1.11"
  title: "EVE Swagger Interface"
host: "esi.evetech.net"
basePath: "/v5"
schemes:
- "https"
paths:
  /characters/{character_id}/:
    get:
      tags:
      - "Character"
      summary: "Get character's public information"
      description: "Public information about a character\n\n---\nAlternate route:\
        \ `/dev/characters/{character_id}/`\n\nAlternate route: `/latest/characters/{character_id}/`\n\
        \nAlternate route: `/legacy/characters/{character_id}/`\n\n---\nThis route\
        \ is cached for up to 86400 seconds"
      operationId: "get_characters_character_id"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      x-cached-seconds: 86400
  /characters/{character_id}/assets/:
    get:
      tags:
      - "Assets"
      summary: "Get character assets"
      description: "Return a list of the characters assets\n\n---\nAlternate route:\
        \ `/dev/characters/{character_id}/assets/`\n\nAlternate route: `/latest/characters/{character_id}/assets/`\n\
        \n---\nThis route is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_assets"
      security:
      - evesso:
        - "esi-assets.read_assets.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
  /characters/{character_id}/cspa/:
    post:
      tags:
      - "Character"
      summary: "Calculate a CSPA charge cost"
      description: "Takes a source character ID in the url and a set of target character\
        \ ID's in the body, returns a CSPA charge cost\n\n---\nAlternate route: `/dev/characters/{character_id}/cspa/`\n\
        \nAlternate route: `/latest/characters/{character_id}/cspa/`\n"
      operationId: "post_characters_character_id_cspa"
      security:
      - evesso:
        - "esi-characters.read_contacts.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
  /characters/{character_id}/notifications/:
    get:
      tags:
      - "Character"
      summary: "Get character notifications"
      description: "Return character notifications\n\n---\nAlternate route: `/dev/characters/{character_id}/notifications/`\n\
        \nAlternate route: `/latest/characters/{character_id}/notifications/`\n\n\
        Alternate route: `/v6/characters/{character_id}/notifications/`\n\n---\nThis\
        \ route is cached for up to 600 seconds"
      operationId: "get_characters_character_id_notifications"
      security:
      - evesso:
        - "esi-characters.read_notifications.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "v6"
      x-cached-seconds: 600
  /characters/{character_id}/wallet/journal/:
    get:
      tags:
      - "Wallet"
      summary: "Get character wallet journal"
      description: "Retrieve the given character's wallet journal going 30 days back\n\
        \n---\nAlternate route: `/legacy/characters/{character_id}/wallet/journal/`\n\
        \n---\nThis route is cached for up to 3600 seconds\n\n---\nWarning: This route\
        \ is deprecated\n\n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/v5/dev/#GET-/characters/{character_id}/wallet/journal/)"
      operationId: "get_characters_character_id_wallet_journal"
      security:
      - evesso:
        - "esi-wallet.read_character_wallet.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
      x-cached-seconds: 3600
  /corporations/{corporation_id}/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation information"
      description: "Public information about a corporation\n\n---\nAlternate route:\
        \ `/dev/corporations/{corporation_id}/`\n\nAlternate route: `/latest/corporations/{corporation_id}/`\n\
        \n---\nThis route is cached for up to 3600 seconds"
      operationId: "get_corporations_corporation_id"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
  /corporations/{corporation_id}/assets/:
    get:
      tags:
      - "Assets"
      summary: "Get corporation assets"
      description: "Return a list of the corporation assets\n\n---\nAlternate route:\
        \ `/dev/corporations/{corporation_id}/assets/`\n\nAlternate route: `/latest/corporations/{corporation_id}/assets/`\n\
        \n---\nThis route is cached for up to 3600 seconds\n\n---\nRequires one of\
        \ the following EVE corporation role(s): Director\n"
      operationId: "get_corporations_corporation_id_assets"
      security:
      - evesso:
        - "esi-assets.read_corporation_assets.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
securityDefinitions:
  evesso:
    type: "oauth2"
    authorizationUrl: "https://login.eveonline.com/v2/oauth/authorize"
    flow: "implicit"
    scopes:
      esi-assets.read_assets.v1: "EVE SSO scope esi-assets.read_assets.v1"
      esi-assets.read_corporation_assets.v1: "EVE SSO scope esi-assets.read_corporation_assets.v1"
      esi-characters.read_contacts.v1: "EVE SSO scope esi-characters.read_contacts.v1"
      esi-characters.read_notifications.v1: "EVE SSO scope esi-characters.read_notifications.v1"
      esi-wallet.read_character_wallet.v1: "EVE SSO scope esi-wallet.read_character_wallet.v1"