---
swagger: "2.0"
info:
  description: "An OpenAPI for EVE Online"
  version: "1.2.9"
  title: "EVE Swagger Interface"
host: "esi.evetech.net"
basePath: "/v4"
schemes:
- "https"
paths:
  /characters/{character_id}/:
    get:
      tags:
      - "Character"
      summary: "Get character's public information"
      description: "Public information about a character\n\n---\nAlternate route:\
        \ `/dev/characters/{character_id}/`\n\nAlternate route: `/latest/characters/{character_id}/`\n\
        \n---\nThis route is cached for up to 86400 seconds"
      operationId: "get_characters_character_id"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 86400
  /characters/{character_id}/cspa/:
    post:
      tags:
      - "Character"
      summary: "Calculate a CSPA charge cost"
      description: "Takes a source character ID in the url and a set of target character\
        \ ID's in the body, returns a CSPA charge cost\n\n---\nAlternate route: `/dev/characters/{character_id}/cspa/`\n\
        \nAlternate route: `/latest/characters/{character_id}/cspa/`\n"
      operationId: "post_characters_character_id_cspa"
      security:
      - evesso:
        - "esi-characters.read_contacts.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
  /characters/{character_id}/notifications/:
    get:
      tags:
      - "Character"
      summary: "Get character notifications"
      description: "Return character notifications\n\n---\nAlternate route: `/legacy/characters/{character_id}/notifications/`\n\
        \n---\nThis route is cached for up to 600 seconds\n\n---\nWarning: This route\
        \ is deprecated\n\n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/v4/dev/#GET-/characters/{character_id}/notifications/)"
      operationId: "get_characters_character_id_notifications"
      security:
      - evesso:
        - "esi-characters.read_notifications.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
      x-cached-seconds: 600
  /characters/{character_id}/skills/:
    get:
      tags:
      - "Skills"
      summary: "Get character skills"
      description: "List all trained skills for the given character\n\n---\nAlternate\
        \ route: `/dev/characters/{character_id}/skills/`\n\nAlternate route: `/latest/characters/{character_id}/skills/`\n\
        \n---\nThis route is cached for up to 120 seconds"
      operationId: "get_characters_character_id_skills"
      security:
      - evesso:
        - "esi-skills.read_skills.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 120
  /corporations/{corporation_id}/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation information"
      description: "Public information about a corporation\n\n---\nAlternate route:\
        \ `/dev/corporations/{corporation_id}/`\n\nAlternate route: `/latest/corporations/{corporation_id}/`\n\
        \n---\nThis route is cached for up to 3600 seconds"
      operationId: "get_corporations_corporation_id"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
  /corporations/{corporation_id}/wallets/{division}/journal/:
    get:
      tags:
      - "Wallet"
      summary: "Get corporation wallet journal"
      description: "Retrieve the given corporation's wallet journal for the given\
        \ division going 30 days back\n\n---\nAlternate route: `/dev/corporations/{corporation_id}/wallets/{division}/journal/`\n\
        \nAlternate route: `/latest/corporations/{corporation_id}/wallets/{division}/journal/`\n\
        \n---\nThis route is cached for up to 3600 seconds\n\n---\nRequires one of\
        \ the following EVE corporation role(s): Accountant, Junior_Accountant\n"
      operationId: "get_corporations_corporation_id_wallets_division_journal"
      security:
      - evesso:
        - "esi-wallet.read_corporation_wallets.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
      x-required-roles:
      - "Accountant"
      - "Junior_Accountant"
  /universe/systems/{system_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get solar system information"
      description: "Get information on a solar system.\n\n---\nAlternate route: `/dev/universe/systems/{system_id}/`\n\
        \nAlternate route: `/latest/universe/systems/{system_id}/`\n\n---\nThis route\
        \ expires daily at 11:05"
      operationId: "get_universe_systems_system_id"
      x-alternate-versions:
      - "dev"
      - "latest"
securityDefinitions:
  evesso:
    type: "oauth2"
    authorizationUrl: "https://login.eveonline.com/v2/oauth/authorize"
    flow: "implicit"
    scopes:
      esi-characters.read_contacts.v1: "EVE SSO scope esi-characters.read_contacts.v1"
      esi-characters.read_notifications.v1: "EVE SSO scope esi-characters.read_notifications.v1"
      esi-skills.read_skills.v1: "EVE SSO scope esi-skills.read_skills.v1"
      esi-wallet.read_corporation_wallets.v1: "EVE SSO scope esi-wallet.read_corporation_wallets.v1"