---
swagger: "2.0"
info:
  description: "An OpenAPI for EVE Online"
  version: "1.12"
  title: "EVE Swagger Interface"
host: "esi.evetech.net"
basePath: "/v4"
schemes:
- "https"
paths:
  /alliances/{alliance_id}/:
    get:
      tags:
      - "Alliance"
      summary: "Get alliance information"
      description: "Public information about an alliance\n\n---\nAlternate route:\
        \ `/dev/alliances/{alliance_id}/`\n\nAlternate route: `/latest/alliances/{alliance_id}/`\n\
        \nAlternate route: `/legacy/alliances/{alliance_id}/`\n\nAlternate route:\
        \ `/v3/alliances/{alliance_id}/`\n\n---\nThis route is cached for up to 3600\
        \ seconds"
      operationId: "get_alliances_alliance_id"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v3"
      x-cached-seconds: 3600
  /characters/{character_id}/assets/:
    get:
      tags:
      - "Assets"
      summary: "Get character assets"
      description: "Return a list of the characters assets\n\n---\nAlternate route:\
        \ `/legacy/characters/{character_id}/assets/`\n\n---\nThis route is cached\
        \ for up to 3600 seconds\n\n---\nWarning: This route is deprecated\n\n---\n\
        [Diff of the upcoming changes](https://esi.evetech.net/diff/v4/dev/#GET-/characters/{character_id}/assets/)"
      operationId: "get_characters_character_id_assets"
      security:
      - evesso:
        - "esi-assets.read_assets.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
      x-cached-seconds: 3600
  /characters/{character_id}/calendar/{event_id}/:
    get:
      tags:
      - "Calendar"
      summary: "Get an event"
      description: "Get all the information for a specific event\n\n---\nAlternate\
        \ route: `/dev/characters/{character_id}/calendar/{event_id}/`\n\nAlternate\
        \ route: `/latest/characters/{character_id}/calendar/{event_id}/`\n\nAlternate\
        \ route: `/legacy/characters/{character_id}/calendar/{event_id}/`\n\nAlternate\
        \ route: `/v3/characters/{character_id}/calendar/{event_id}/`\n\n---\nThis\
        \ route is cached for up to 5 seconds"
      operationId: "get_characters_character_id_calendar_event_id"
      security:
      - evesso:
        - "esi-calendar.read_calendar_events.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v3"
      x-cached-seconds: 5
    put:
      tags:
      - "Calendar"
      summary: "Respond to an event"
      description: "Set your response status to an event\n\n---\nAlternate route:\
        \ `/dev/characters/{character_id}/calendar/{event_id}/`\n\nAlternate route:\
        \ `/latest/characters/{character_id}/calendar/{event_id}/`\n\nAlternate route:\
        \ `/legacy/characters/{character_id}/calendar/{event_id}/`\n\nAlternate route:\
        \ `/v3/characters/{character_id}/calendar/{event_id}/`\n\n---\nThis route\
        \ is cached for up to 5 seconds"
      operationId: "put_characters_character_id_calendar_event_id"
      security:
      - evesso:
        - "esi-calendar.respond_calendar_events.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "legacy"
      - "v3"
      x-cached-seconds: 5
  /characters/{character_id}/clones/:
    get:
      tags:
      - "Clones"
      summary: "Get clones"
      description: "A list of the character's clones\n\n---\nAlternate route: `/dev/characters/{character_id}/clones/`\n\
        \nAlternate route: `/latest/characters/{character_id}/clones/`\n\nAlternate\
        \ route: `/v3/characters/{character_id}/clones/`\n\n---\nThis route is cached\
        \ for up to 120 seconds"
      operationId: "get_characters_character_id_clones"
      security:
      - evesso:
        - "esi-clones.read_clones.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      - "v3"
      x-cached-seconds: 120
  /characters/{character_id}/cspa/:
    post:
      tags:
      - "Character"
      summary: "Calculate a CSPA charge cost"
      description: "Takes a source character ID in the url and a set of target character\
        \ ID's in the body, returns a CSPA charge cost\n\n---\nAlternate route: `/legacy/characters/{character_id}/cspa/`\n\
        \n\n---\nWarning: This route is deprecated\n\n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/v4/dev/#POST-/characters/{character_id}/cspa/)"
      operationId: "post_characters_character_id_cspa"
      security:
      - evesso:
        - "esi-characters.read_contacts.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
  /characters/{character_id}/notifications/:
    get:
      tags:
      - "Character"
      summary: "Get character notifications"
      description: "Return character notifications\n\n---\nAlternate route: `/legacy/characters/{character_id}/notifications/`\n\
        \n---\nThis route is cached for up to 600 seconds\n\n---\nWarning: This route\
        \ is deprecated\n\n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/v4/dev/#GET-/characters/{character_id}/notifications/)"
      operationId: "get_characters_character_id_notifications"
      security:
      - evesso:
        - "esi-characters.read_notifications.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
      x-cached-seconds: 600
  /characters/{character_id}/skills/:
    get:
      tags:
      - "Skills"
      summary: "Get character skills"
      description: "List all trained skills for the given character\n\n---\nAlternate\
        \ route: `/dev/characters/{character_id}/skills/`\n\nAlternate route: `/latest/characters/{character_id}/skills/`\n\
        \n---\nThis route is cached for up to 120 seconds"
      operationId: "get_characters_character_id_skills"
      security:
      - evesso:
        - "esi-skills.read_skills.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 120
  /corporations/{corporation_id}/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation information"
      description: "Public information about a corporation\n\n---\nAlternate route:\
        \ `/legacy/corporations/{corporation_id}/`\n\n---\nThis route is cached for\
        \ up to 3600 seconds\n\n---\nWarning: This route is deprecated\n\n---\n[Diff\
        \ of the upcoming changes](https://esi.evetech.net/diff/v4/dev/#GET-/corporations/{corporation_id}/)"
      operationId: "get_corporations_corporation_id"
      deprecated: true
      x-alternate-versions:
      - "legacy"
      x-cached-seconds: 3600
  /corporations/{corporation_id}/assets/:
    get:
      tags:
      - "Assets"
      summary: "Get corporation assets"
      description: "Return a list of the corporation assets\n\n---\nAlternate route:\
        \ `/legacy/corporations/{corporation_id}/assets/`\n\n---\nThis route is cached\
        \ for up to 3600 seconds\n\n---\nRequires one of the following EVE corporation\
        \ role(s): Director\n\n\n---\nWarning: This route is deprecated\n\n---\n[Diff\
        \ of the upcoming changes](https://esi.evetech.net/diff/v4/dev/#GET-/corporations/{corporation_id}/assets/)"
      operationId: "get_corporations_corporation_id_assets"
      security:
      - evesso:
        - "esi-assets.read_corporation_assets.v1"
      deprecated: true
      x-alternate-versions:
      - "legacy"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /corporations/{corporation_id}/members/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation members"
      description: "Return the current member list of a corporation, the token's character\
        \ need to be a member of the corporation.\n\n---\nAlternate route: `/dev/corporations/{corporation_id}/members/`\n\
        \nAlternate route: `/latest/corporations/{corporation_id}/members/`\n\n---\n\
        This route is cached for up to 3600 seconds"
      operationId: "get_corporations_corporation_id_members"
      security:
      - evesso:
        - "esi-corporations.read_corporation_membership.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
  /corporations/{corporation_id}/structures/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation structures"
      description: "Get a list of corporation structures. This route's version includes\
        \ the changes to structures detailed in this blog: https://www.eveonline.com/article/upwell-2.0-structures-changes-coming-on-february-13th\n\
        \n---\nAlternate route: `/dev/corporations/{corporation_id}/structures/`\n\
        \nAlternate route: `/latest/corporations/{corporation_id}/structures/`\n\n\
        ---\nThis route is cached for up to 3600 seconds\n\n---\nRequires one of the\
        \ following EVE corporation role(s): Station_Manager\n"
      operationId: "get_corporations_corporation_id_structures"
      security:
      - evesso:
        - "esi-corporations.read_structures.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
      x-required-roles:
      - "Station_Manager"
  /corporations/{corporation_id}/wallets/{division}/journal/:
    get:
      tags:
      - "Wallet"
      summary: "Get corporation wallet journal"
      description: "Retrieve the given corporation's wallet journal for the given\
        \ division going 30 days back\n\n---\nAlternate route: `/dev/corporations/{corporation_id}/wallets/{division}/journal/`\n\
        \nAlternate route: `/latest/corporations/{corporation_id}/wallets/{division}/journal/`\n\
        \n---\nThis route is cached for up to 3600 seconds\n\n---\nRequires one of\
        \ the following EVE corporation role(s): Accountant, Junior_Accountant\n"
      operationId: "get_corporations_corporation_id_wallets_division_journal"
      security:
      - evesso:
        - "esi-wallet.read_corporation_wallets.v1"
      x-alternate-versions:
      - "dev"
      - "latest"
      x-cached-seconds: 3600
      x-required-roles:
      - "Accountant"
      - "Junior_Accountant"
  /universe/systems/{system_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get solar system information"
      description: "Get information on a solar system.\n\n---\nAlternate route: `/dev/universe/systems/{system_id}/`\n\
        \nAlternate route: `/latest/universe/systems/{system_id}/`\n\n---\nThis route\
        \ expires daily at 11:05"
      operationId: "get_universe_systems_system_id"
      x-alternate-versions:
      - "dev"
      - "latest"
securityDefinitions:
  evesso:
    type: "oauth2"
    authorizationUrl: "https://login.eveonline.com/v2/oauth/authorize"
    flow: "implicit"
    scopes:
      esi-assets.read_assets.v1: "EVE SSO scope esi-assets.read_assets.v1"
      esi-assets.read_corporation_assets.v1: "EVE SSO scope esi-assets.read_corporation_assets.v1"
      esi-calendar.read_calendar_events.v1: "EVE SSO scope esi-calendar.read_calendar_events.v1"
      esi-calendar.respond_calendar_events.v1: "EVE SSO scope esi-calendar.respond_calendar_events.v1"
      esi-characters.read_contacts.v1: "EVE SSO scope esi-characters.read_contacts.v1"
      esi-characters.read_notifications.v1: "EVE SSO scope esi-characters.read_notifications.v1"
      esi-clones.read_clones.v1: "EVE SSO scope esi-clones.read_clones.v1"
      esi-corporations.read_corporation_membership.v1: "EVE SSO scope esi-corporations.read_corporation_membership.v1"
      esi-corporations.read_structures.v1: "EVE SSO scope esi-corporations.read_structures.v1"
      esi-skills.read_skills.v1: "EVE SSO scope esi-skills.read_skills.v1"
      esi-wallet.read_corporation_wallets.v1: "EVE SSO scope esi-wallet.read_corporation_wallets.v1"